/**
 * AUTO-GENERATED by scripts/generateMockData.ts — do not hand-edit.
 * Regenerate with: npm run generate:data
 *
 * Conforms to the data contract in spec/04-data-spec.md.
 */

import type { TrainAvailability } from '../types/domain';

export const trainAvailability: TrainAvailability[] = [
  {
    "trainNumber": "12760",
    "journeyDate": "2026-08-24",
    "travelClass": "3A",
    "quota": "GENERAL",
    "status": "CNF",
    "confirmedSeatsRemaining": 14,
    "confirmationLikelihood": 1,
    "fareAmount": 1240
  },
  {
    "trainNumber": "17654",
    "journeyDate": "2026-08-24",
    "travelClass": "3A",
    "quota": "GENERAL",
    "status": "GNWL",
    "waitlistPosition": 42,
    "confirmationLikelihood": 0.4,
    "fareAmount": 780
  },
  {
    "trainNumber": "12604",
    "journeyDate": "2026-08-24",
    "travelClass": "3A",
    "quota": "GENERAL",
    "status": "CNF",
    "confirmedSeatsRemaining": 6,
    "confirmationLikelihood": 1,
    "fareAmount": 1680
  },
  {
    "trainNumber": "12759",
    "journeyDate": "2026-08-25",
    "travelClass": "3A",
    "quota": "GENERAL",
    "status": "GNWL",
    "waitlistPosition": 24,
    "confirmationLikelihood": 0.61,
    "fareAmount": 960
  },
  {
    "trainNumber": "17406",
    "journeyDate": "2026-08-25",
    "travelClass": "3A",
    "quota": "GENERAL",
    "status": "RAC",
    "racPosition": 14,
    "confirmationLikelihood": 0.8,
    "fareAmount": 650
  },
  {
    "trainNumber": "17015",
    "journeyDate": "2026-08-27",
    "travelClass": "SL",
    "quota": "GENERAL",
    "status": "GNWL",
    "waitlistPosition": 8,
    "confirmationLikelihood": 0.8,
    "fareAmount": 700
  },
  {
    "trainNumber": "12703",
    "journeyDate": "2026-08-27",
    "travelClass": "3A",
    "quota": "GENERAL",
    "status": "CNF",
    "confirmedSeatsRemaining": 9,
    "confirmationLikelihood": 1,
    "fareAmount": 1100
  },
  {
    "trainNumber": "12841",
    "journeyDate": "2026-08-25",
    "travelClass": "3A",
    "quota": "GENERAL",
    "status": "SOLD_OUT",
    "confirmationLikelihood": 0,
    "fareAmount": 890
  },
  {
    "trainNumber": "12728",
    "journeyDate": "2026-08-23",
    "travelClass": "3A",
    "quota": "GENERAL",
    "status": "CNF",
    "confirmedSeatsRemaining": 11,
    "confirmationLikelihood": 1,
    "fareAmount": 1350
  },
  {
    "trainNumber": "12766",
    "journeyDate": "2026-08-23",
    "travelClass": "3A",
    "quota": "GENERAL",
    "status": "GNWL",
    "waitlistPosition": 12,
    "confirmationLikelihood": 0.76,
    "fareAmount": 980
  },
  {
    "trainNumber": "17603",
    "journeyDate": "2026-08-23",
    "travelClass": "2A",
    "quota": "GENERAL",
    "status": "CNF",
    "confirmedSeatsRemaining": 5,
    "confirmationLikelihood": 1,
    "fareAmount": 2100
  },
  {
    "trainNumber": "12864",
    "journeyDate": "2026-08-24",
    "travelClass": "3A",
    "quota": "GENERAL",
    "status": "GNWL",
    "waitlistPosition": 5,
    "confirmationLikelihood": 0.84,
    "fareAmount": 1450
  },
  {
    "trainNumber": "12246",
    "journeyDate": "2026-08-24",
    "travelClass": "3A",
    "quota": "GENERAL",
    "status": "PQWL",
    "waitlistPosition": 20,
    "confirmationLikelihood": 0.46,
    "fareAmount": 1590
  },
  {
    "trainNumber": "18646",
    "journeyDate": "2026-08-24",
    "travelClass": "3A",
    "quota": "GENERAL",
    "status": "RLWL",
    "waitlistPosition": 35,
    "confirmationLikelihood": 0.18,
    "fareAmount": 1180
  },
  {
    "trainNumber": "12759",
    "journeyDate": "2026-08-23",
    "travelClass": "3A",
    "quota": "TATKAL",
    "status": "TQWL",
    "waitlistPosition": 6,
    "confirmationLikelihood": 0.38,
    "fareAmount": 1050
  },
  {
    "trainNumber": "17406",
    "journeyDate": "2026-08-23",
    "travelClass": "3A",
    "quota": "TATKAL",
    "status": "CNF",
    "confirmedSeatsRemaining": 4,
    "confirmationLikelihood": 1,
    "fareAmount": 1450
  },
  {
    "trainNumber": "17015",
    "journeyDate": "2026-08-23",
    "travelClass": "3A",
    "quota": "TATKAL",
    "status": "CNF",
    "confirmedSeatsRemaining": 8,
    "confirmationLikelihood": 1,
    "fareAmount": 820
  },
  {
    "trainNumber": "12760",
    "journeyDate": "2026-08-23",
    "travelClass": "3A",
    "quota": "TATKAL",
    "status": "SOLD_OUT",
    "confirmationLikelihood": 0,
    "fareAmount": 1450
  },
  {
    "trainNumber": "17654",
    "journeyDate": "2026-08-23",
    "travelClass": "3A",
    "quota": "TATKAL",
    "status": "CNF",
    "confirmedSeatsRemaining": 3,
    "confirmationLikelihood": 1,
    "fareAmount": 990
  },
  {
    "trainNumber": "12604",
    "journeyDate": "2026-08-23",
    "travelClass": "3A",
    "quota": "TATKAL",
    "status": "CNF",
    "confirmedSeatsRemaining": 2,
    "confirmationLikelihood": 1,
    "fareAmount": 1980
  },
  {
    "trainNumber": "20000",
    "journeyDate": "2026-08-24",
    "travelClass": "SL",
    "quota": "GENERAL",
    "fareAmount": 350,
    "status": "CNF",
    "confirmedSeatsRemaining": 1,
    "confirmationLikelihood": 1
  },
  {
    "trainNumber": "20000",
    "journeyDate": "2026-08-26",
    "travelClass": "SL",
    "quota": "GENERAL",
    "fareAmount": 367,
    "status": "RAC",
    "racPosition": 4,
    "confirmationLikelihood": 0.6
  },
  {
    "trainNumber": "20000",
    "journeyDate": "2026-08-28",
    "travelClass": "SL",
    "quota": "GENERAL",
    "fareAmount": 384,
    "status": "GNWL",
    "waitlistPosition": 3,
    "confirmationLikelihood": 0.86
  },
  {
    "trainNumber": "20000",
    "journeyDate": "2026-08-24",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 463,
    "status": "RAC",
    "racPosition": 1,
    "confirmationLikelihood": 0.6
  },
  {
    "trainNumber": "20000",
    "journeyDate": "2026-08-26",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 480,
    "status": "GNWL",
    "waitlistPosition": 2,
    "confirmationLikelihood": 0.88
  },
  {
    "trainNumber": "20000",
    "journeyDate": "2026-08-28",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 497,
    "status": "PQWL",
    "waitlistPosition": 3,
    "confirmationLikelihood": 0.66
  },
  {
    "trainNumber": "20001",
    "journeyDate": "2026-08-24",
    "travelClass": "SL",
    "quota": "GENERAL",
    "fareAmount": 379,
    "status": "RAC",
    "racPosition": 2,
    "confirmationLikelihood": 0.65
  },
  {
    "trainNumber": "20001",
    "journeyDate": "2026-08-26",
    "travelClass": "SL",
    "quota": "GENERAL",
    "fareAmount": 396,
    "status": "GNWL",
    "waitlistPosition": 5,
    "confirmationLikelihood": 0.84
  },
  {
    "trainNumber": "20001",
    "journeyDate": "2026-08-28",
    "travelClass": "SL",
    "quota": "GENERAL",
    "fareAmount": 413,
    "status": "PQWL",
    "waitlistPosition": 8,
    "confirmationLikelihood": 0.6
  },
  {
    "trainNumber": "20001",
    "journeyDate": "2026-08-24",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 492,
    "status": "GNWL",
    "waitlistPosition": 4,
    "confirmationLikelihood": 0.85
  },
  {
    "trainNumber": "20001",
    "journeyDate": "2026-08-26",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 509,
    "status": "PQWL",
    "waitlistPosition": 7,
    "confirmationLikelihood": 0.62
  },
  {
    "trainNumber": "20001",
    "journeyDate": "2026-08-28",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 526,
    "status": "RLWL",
    "waitlistPosition": 10,
    "confirmationLikelihood": 0.48
  },
  {
    "trainNumber": "20001",
    "journeyDate": "2026-08-24",
    "travelClass": "2A",
    "quota": "GENERAL",
    "fareAmount": 605,
    "status": "PQWL",
    "waitlistPosition": 6,
    "confirmationLikelihood": 0.63
  },
  {
    "trainNumber": "20001",
    "journeyDate": "2026-08-26",
    "travelClass": "2A",
    "quota": "GENERAL",
    "fareAmount": 622,
    "status": "RLWL",
    "waitlistPosition": 9,
    "confirmationLikelihood": 0.49
  },
  {
    "trainNumber": "20001",
    "journeyDate": "2026-08-28",
    "travelClass": "2A",
    "quota": "GENERAL",
    "fareAmount": 639,
    "status": "SOLD_OUT",
    "confirmationLikelihood": 0
  },
  {
    "trainNumber": "20002",
    "journeyDate": "2026-08-24",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 408,
    "status": "GNWL",
    "waitlistPosition": 7,
    "confirmationLikelihood": 0.82
  },
  {
    "trainNumber": "20002",
    "journeyDate": "2026-08-26",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 425,
    "status": "PQWL",
    "waitlistPosition": 12,
    "confirmationLikelihood": 0.56
  },
  {
    "trainNumber": "20002",
    "journeyDate": "2026-08-28",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 442,
    "status": "RLWL",
    "waitlistPosition": 17,
    "confirmationLikelihood": 0.4
  },
  {
    "trainNumber": "20002",
    "journeyDate": "2026-08-24",
    "travelClass": "2A",
    "quota": "GENERAL",
    "fareAmount": 521,
    "status": "PQWL",
    "waitlistPosition": 11,
    "confirmationLikelihood": 0.57
  },
  {
    "trainNumber": "20002",
    "journeyDate": "2026-08-26",
    "travelClass": "2A",
    "quota": "GENERAL",
    "fareAmount": 538,
    "status": "RLWL",
    "waitlistPosition": 16,
    "confirmationLikelihood": 0.41
  },
  {
    "trainNumber": "20002",
    "journeyDate": "2026-08-28",
    "travelClass": "2A",
    "quota": "GENERAL",
    "fareAmount": 555,
    "status": "SOLD_OUT",
    "confirmationLikelihood": 0
  },
  {
    "trainNumber": "20003",
    "journeyDate": "2026-08-24",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 437,
    "status": "PQWL",
    "waitlistPosition": 16,
    "confirmationLikelihood": 0.51
  },
  {
    "trainNumber": "20003",
    "journeyDate": "2026-08-26",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 454,
    "status": "RLWL",
    "waitlistPosition": 23,
    "confirmationLikelihood": 0.32
  },
  {
    "trainNumber": "20003",
    "journeyDate": "2026-08-28",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 471,
    "status": "SOLD_OUT",
    "confirmationLikelihood": 0
  },
  {
    "trainNumber": "20003",
    "journeyDate": "2026-08-24",
    "travelClass": "2A",
    "quota": "GENERAL",
    "fareAmount": 550,
    "status": "RLWL",
    "waitlistPosition": 22,
    "confirmationLikelihood": 0.34
  },
  {
    "trainNumber": "20003",
    "journeyDate": "2026-08-26",
    "travelClass": "2A",
    "quota": "GENERAL",
    "fareAmount": 567,
    "status": "SOLD_OUT",
    "confirmationLikelihood": 0
  },
  {
    "trainNumber": "20003",
    "journeyDate": "2026-08-28",
    "travelClass": "2A",
    "quota": "GENERAL",
    "fareAmount": 584,
    "status": "CNF",
    "confirmedSeatsRemaining": 6,
    "confirmationLikelihood": 1
  },
  {
    "trainNumber": "20003",
    "journeyDate": "2026-08-24",
    "travelClass": "1A",
    "quota": "GENERAL",
    "fareAmount": 663,
    "status": "SOLD_OUT",
    "confirmationLikelihood": 0
  },
  {
    "trainNumber": "20003",
    "journeyDate": "2026-08-26",
    "travelClass": "1A",
    "quota": "GENERAL",
    "fareAmount": 680,
    "status": "CNF",
    "confirmedSeatsRemaining": 5,
    "confirmationLikelihood": 1
  },
  {
    "trainNumber": "20003",
    "journeyDate": "2026-08-28",
    "travelClass": "1A",
    "quota": "GENERAL",
    "fareAmount": 697,
    "status": "RAC",
    "racPosition": 10,
    "confirmationLikelihood": 0.75
  },
  {
    "trainNumber": "20004",
    "journeyDate": "2026-08-24",
    "travelClass": "SL",
    "quota": "GENERAL",
    "fareAmount": 466,
    "status": "RLWL",
    "waitlistPosition": 29,
    "confirmationLikelihood": 0.25
  },
  {
    "trainNumber": "20004",
    "journeyDate": "2026-08-26",
    "travelClass": "SL",
    "quota": "GENERAL",
    "fareAmount": 483,
    "status": "SOLD_OUT",
    "confirmationLikelihood": 0
  },
  {
    "trainNumber": "20004",
    "journeyDate": "2026-08-28",
    "travelClass": "SL",
    "quota": "GENERAL",
    "fareAmount": 500,
    "status": "CNF",
    "confirmedSeatsRemaining": 7,
    "confirmationLikelihood": 1
  },
  {
    "trainNumber": "20005",
    "journeyDate": "2026-08-24",
    "travelClass": "CC",
    "quota": "GENERAL",
    "fareAmount": 495,
    "status": "SOLD_OUT",
    "confirmationLikelihood": 0
  },
  {
    "trainNumber": "20005",
    "journeyDate": "2026-08-26",
    "travelClass": "CC",
    "quota": "GENERAL",
    "fareAmount": 512,
    "status": "CNF",
    "confirmedSeatsRemaining": 7,
    "confirmationLikelihood": 1
  },
  {
    "trainNumber": "20005",
    "journeyDate": "2026-08-28",
    "travelClass": "CC",
    "quota": "GENERAL",
    "fareAmount": 529,
    "status": "RAC",
    "racPosition": 12,
    "confirmationLikelihood": 0.65
  },
  {
    "trainNumber": "20006",
    "journeyDate": "2026-08-24",
    "travelClass": "SL",
    "quota": "GENERAL",
    "fareAmount": 524,
    "status": "CNF",
    "confirmedSeatsRemaining": 7,
    "confirmationLikelihood": 1
  },
  {
    "trainNumber": "20006",
    "journeyDate": "2026-08-26",
    "travelClass": "SL",
    "quota": "GENERAL",
    "fareAmount": 541,
    "status": "RAC",
    "racPosition": 10,
    "confirmationLikelihood": 0.7
  },
  {
    "trainNumber": "20006",
    "journeyDate": "2026-08-28",
    "travelClass": "SL",
    "quota": "GENERAL",
    "fareAmount": 558,
    "status": "GNWL",
    "waitlistPosition": 21,
    "confirmationLikelihood": 0.65
  },
  {
    "trainNumber": "20006",
    "journeyDate": "2026-08-24",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 637,
    "status": "RAC",
    "racPosition": 7,
    "confirmationLikelihood": 0.7
  },
  {
    "trainNumber": "20006",
    "journeyDate": "2026-08-26",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 654,
    "status": "GNWL",
    "waitlistPosition": 20,
    "confirmationLikelihood": 0.66
  },
  {
    "trainNumber": "20006",
    "journeyDate": "2026-08-28",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 671,
    "status": "PQWL",
    "waitlistPosition": 33,
    "confirmationLikelihood": 0.3
  },
  {
    "trainNumber": "20006",
    "journeyDate": "2026-08-24",
    "travelClass": "2A",
    "quota": "GENERAL",
    "fareAmount": 750,
    "status": "GNWL",
    "waitlistPosition": 19,
    "confirmationLikelihood": 0.67
  },
  {
    "trainNumber": "20006",
    "journeyDate": "2026-08-26",
    "travelClass": "2A",
    "quota": "GENERAL",
    "fareAmount": 767,
    "status": "PQWL",
    "waitlistPosition": 32,
    "confirmationLikelihood": 0.32
  },
  {
    "trainNumber": "20006",
    "journeyDate": "2026-08-28",
    "travelClass": "2A",
    "quota": "GENERAL",
    "fareAmount": 784,
    "status": "RLWL",
    "waitlistPosition": 45,
    "confirmationLikelihood": 0.06
  },
  {
    "trainNumber": "20006",
    "journeyDate": "2026-08-24",
    "travelClass": "1A",
    "quota": "GENERAL",
    "fareAmount": 863,
    "status": "PQWL",
    "waitlistPosition": 31,
    "confirmationLikelihood": 0.33
  },
  {
    "trainNumber": "20006",
    "journeyDate": "2026-08-26",
    "travelClass": "1A",
    "quota": "GENERAL",
    "fareAmount": 880,
    "status": "RLWL",
    "waitlistPosition": 44,
    "confirmationLikelihood": 0.07
  },
  {
    "trainNumber": "20006",
    "journeyDate": "2026-08-28",
    "travelClass": "1A",
    "quota": "GENERAL",
    "fareAmount": 897,
    "status": "SOLD_OUT",
    "confirmationLikelihood": 0
  },
  {
    "trainNumber": "20007",
    "journeyDate": "2026-08-24",
    "travelClass": "SL",
    "quota": "GENERAL",
    "fareAmount": 553,
    "status": "RAC",
    "racPosition": 8,
    "confirmationLikelihood": 0.75
  },
  {
    "trainNumber": "20007",
    "journeyDate": "2026-08-26",
    "travelClass": "SL",
    "quota": "GENERAL",
    "fareAmount": 570,
    "status": "GNWL",
    "waitlistPosition": 23,
    "confirmationLikelihood": 0.62
  },
  {
    "trainNumber": "20007",
    "journeyDate": "2026-08-28",
    "travelClass": "SL",
    "quota": "GENERAL",
    "fareAmount": 587,
    "status": "PQWL",
    "waitlistPosition": 38,
    "confirmationLikelihood": 0.24
  },
  {
    "trainNumber": "20007",
    "journeyDate": "2026-08-24",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 666,
    "status": "GNWL",
    "waitlistPosition": 22,
    "confirmationLikelihood": 0.64
  },
  {
    "trainNumber": "20007",
    "journeyDate": "2026-08-26",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 683,
    "status": "PQWL",
    "waitlistPosition": 37,
    "confirmationLikelihood": 0.26
  },
  {
    "trainNumber": "20007",
    "journeyDate": "2026-08-28",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 700,
    "status": "RLWL",
    "waitlistPosition": 52,
    "confirmationLikelihood": 0.05
  },
  {
    "trainNumber": "20008",
    "journeyDate": "2026-08-24",
    "travelClass": "SL",
    "quota": "GENERAL",
    "fareAmount": 582,
    "status": "GNWL",
    "waitlistPosition": 25,
    "confirmationLikelihood": 0.6
  },
  {
    "trainNumber": "20008",
    "journeyDate": "2026-08-26",
    "travelClass": "SL",
    "quota": "GENERAL",
    "fareAmount": 599,
    "status": "PQWL",
    "waitlistPosition": 42,
    "confirmationLikelihood": 0.2
  },
  {
    "trainNumber": "20008",
    "journeyDate": "2026-08-28",
    "travelClass": "SL",
    "quota": "GENERAL",
    "fareAmount": 616,
    "status": "RLWL",
    "waitlistPosition": 59,
    "confirmationLikelihood": 0.05
  },
  {
    "trainNumber": "20008",
    "journeyDate": "2026-08-24",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 695,
    "status": "PQWL",
    "waitlistPosition": 41,
    "confirmationLikelihood": 0.21
  },
  {
    "trainNumber": "20008",
    "journeyDate": "2026-08-26",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 712,
    "status": "RLWL",
    "waitlistPosition": 58,
    "confirmationLikelihood": 0.05
  },
  {
    "trainNumber": "20008",
    "journeyDate": "2026-08-28",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 729,
    "status": "SOLD_OUT",
    "confirmationLikelihood": 0
  },
  {
    "trainNumber": "20008",
    "journeyDate": "2026-08-24",
    "travelClass": "2A",
    "quota": "GENERAL",
    "fareAmount": 808,
    "status": "RLWL",
    "waitlistPosition": 57,
    "confirmationLikelihood": 0.05
  },
  {
    "trainNumber": "20008",
    "journeyDate": "2026-08-26",
    "travelClass": "2A",
    "quota": "GENERAL",
    "fareAmount": 825,
    "status": "SOLD_OUT",
    "confirmationLikelihood": 0
  },
  {
    "trainNumber": "20008",
    "journeyDate": "2026-08-28",
    "travelClass": "2A",
    "quota": "GENERAL",
    "fareAmount": 842,
    "status": "CNF",
    "confirmedSeatsRemaining": 11,
    "confirmationLikelihood": 1
  },
  {
    "trainNumber": "20009",
    "journeyDate": "2026-08-24",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 611,
    "status": "PQWL",
    "waitlistPosition": 46,
    "confirmationLikelihood": 0.15
  },
  {
    "trainNumber": "20009",
    "journeyDate": "2026-08-26",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 628,
    "status": "RLWL",
    "waitlistPosition": 65,
    "confirmationLikelihood": 0.05
  },
  {
    "trainNumber": "20009",
    "journeyDate": "2026-08-28",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 645,
    "status": "SOLD_OUT",
    "confirmationLikelihood": 0
  },
  {
    "trainNumber": "20009",
    "journeyDate": "2026-08-24",
    "travelClass": "2A",
    "quota": "GENERAL",
    "fareAmount": 724,
    "status": "RLWL",
    "waitlistPosition": 64,
    "confirmationLikelihood": 0.05
  },
  {
    "trainNumber": "20009",
    "journeyDate": "2026-08-26",
    "travelClass": "2A",
    "quota": "GENERAL",
    "fareAmount": 741,
    "status": "SOLD_OUT",
    "confirmationLikelihood": 0
  },
  {
    "trainNumber": "20009",
    "journeyDate": "2026-08-28",
    "travelClass": "2A",
    "quota": "GENERAL",
    "fareAmount": 758,
    "status": "CNF",
    "confirmedSeatsRemaining": 12,
    "confirmationLikelihood": 1
  },
  {
    "trainNumber": "20010",
    "journeyDate": "2026-08-24",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 640,
    "status": "RLWL",
    "waitlistPosition": 71,
    "confirmationLikelihood": 0.05
  },
  {
    "trainNumber": "20010",
    "journeyDate": "2026-08-26",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 657,
    "status": "SOLD_OUT",
    "confirmationLikelihood": 0
  },
  {
    "trainNumber": "20010",
    "journeyDate": "2026-08-28",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 674,
    "status": "CNF",
    "confirmedSeatsRemaining": 13,
    "confirmationLikelihood": 1
  },
  {
    "trainNumber": "20010",
    "journeyDate": "2026-08-24",
    "travelClass": "2A",
    "quota": "GENERAL",
    "fareAmount": 753,
    "status": "SOLD_OUT",
    "confirmationLikelihood": 0
  },
  {
    "trainNumber": "20010",
    "journeyDate": "2026-08-26",
    "travelClass": "2A",
    "quota": "GENERAL",
    "fareAmount": 770,
    "status": "CNF",
    "confirmedSeatsRemaining": 12,
    "confirmationLikelihood": 1
  },
  {
    "trainNumber": "20010",
    "journeyDate": "2026-08-28",
    "travelClass": "2A",
    "quota": "GENERAL",
    "fareAmount": 787,
    "status": "RAC",
    "racPosition": 17,
    "confirmationLikelihood": 0.7
  },
  {
    "trainNumber": "20010",
    "journeyDate": "2026-08-24",
    "travelClass": "1A",
    "quota": "GENERAL",
    "fareAmount": 866,
    "status": "CNF",
    "confirmedSeatsRemaining": 11,
    "confirmationLikelihood": 1
  },
  {
    "trainNumber": "20010",
    "journeyDate": "2026-08-26",
    "travelClass": "1A",
    "quota": "GENERAL",
    "fareAmount": 883,
    "status": "RAC",
    "racPosition": 14,
    "confirmationLikelihood": 0.7
  },
  {
    "trainNumber": "20010",
    "journeyDate": "2026-08-28",
    "travelClass": "1A",
    "quota": "GENERAL",
    "fareAmount": 900,
    "status": "GNWL",
    "waitlistPosition": 33,
    "confirmationLikelihood": 0.5
  },
  {
    "trainNumber": "20011",
    "journeyDate": "2026-08-24",
    "travelClass": "SL",
    "quota": "GENERAL",
    "fareAmount": 669,
    "status": "SOLD_OUT",
    "confirmationLikelihood": 0
  },
  {
    "trainNumber": "20011",
    "journeyDate": "2026-08-26",
    "travelClass": "SL",
    "quota": "GENERAL",
    "fareAmount": 686,
    "status": "CNF",
    "confirmedSeatsRemaining": 13,
    "confirmationLikelihood": 1
  },
  {
    "trainNumber": "20011",
    "journeyDate": "2026-08-28",
    "travelClass": "SL",
    "quota": "GENERAL",
    "fareAmount": 703,
    "status": "RAC",
    "racPosition": 18,
    "confirmationLikelihood": 0.75
  },
  {
    "trainNumber": "20012",
    "journeyDate": "2026-08-24",
    "travelClass": "CC",
    "quota": "GENERAL",
    "fareAmount": 698,
    "status": "CNF",
    "confirmedSeatsRemaining": 13,
    "confirmationLikelihood": 1
  },
  {
    "trainNumber": "20012",
    "journeyDate": "2026-08-26",
    "travelClass": "CC",
    "quota": "GENERAL",
    "fareAmount": 715,
    "status": "RAC",
    "racPosition": 16,
    "confirmationLikelihood": 0.6
  },
  {
    "trainNumber": "20012",
    "journeyDate": "2026-08-28",
    "travelClass": "CC",
    "quota": "GENERAL",
    "fareAmount": 732,
    "status": "GNWL",
    "waitlistPosition": 39,
    "confirmationLikelihood": 0.43
  },
  {
    "trainNumber": "20013",
    "journeyDate": "2026-08-24",
    "travelClass": "SL",
    "quota": "GENERAL",
    "fareAmount": 727,
    "status": "RAC",
    "racPosition": 14,
    "confirmationLikelihood": 0.65
  },
  {
    "trainNumber": "20013",
    "journeyDate": "2026-08-26",
    "travelClass": "SL",
    "quota": "GENERAL",
    "fareAmount": 744,
    "status": "GNWL",
    "waitlistPosition": 41,
    "confirmationLikelihood": 0.41
  },
  {
    "trainNumber": "20013",
    "journeyDate": "2026-08-28",
    "travelClass": "SL",
    "quota": "GENERAL",
    "fareAmount": 761,
    "status": "PQWL",
    "waitlistPosition": 68,
    "confirmationLikelihood": 0.05
  },
  {
    "trainNumber": "20013",
    "journeyDate": "2026-08-24",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 840,
    "status": "GNWL",
    "waitlistPosition": 40,
    "confirmationLikelihood": 0.42
  },
  {
    "trainNumber": "20013",
    "journeyDate": "2026-08-26",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 857,
    "status": "PQWL",
    "waitlistPosition": 67,
    "confirmationLikelihood": 0.05
  },
  {
    "trainNumber": "20013",
    "journeyDate": "2026-08-28",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 874,
    "status": "RLWL",
    "waitlistPosition": 14,
    "confirmationLikelihood": 0.43
  },
  {
    "trainNumber": "20013",
    "journeyDate": "2026-08-24",
    "travelClass": "2A",
    "quota": "GENERAL",
    "fareAmount": 953,
    "status": "PQWL",
    "waitlistPosition": 66,
    "confirmationLikelihood": 0.05
  },
  {
    "trainNumber": "20013",
    "journeyDate": "2026-08-26",
    "travelClass": "2A",
    "quota": "GENERAL",
    "fareAmount": 970,
    "status": "RLWL",
    "waitlistPosition": 13,
    "confirmationLikelihood": 0.44
  },
  {
    "trainNumber": "20013",
    "journeyDate": "2026-08-28",
    "travelClass": "2A",
    "quota": "GENERAL",
    "fareAmount": 987,
    "status": "SOLD_OUT",
    "confirmationLikelihood": 0
  },
  {
    "trainNumber": "20013",
    "journeyDate": "2026-08-24",
    "travelClass": "1A",
    "quota": "GENERAL",
    "fareAmount": 1066,
    "status": "RLWL",
    "waitlistPosition": 12,
    "confirmationLikelihood": 0.46
  },
  {
    "trainNumber": "20013",
    "journeyDate": "2026-08-26",
    "travelClass": "1A",
    "quota": "GENERAL",
    "fareAmount": 1083,
    "status": "SOLD_OUT",
    "confirmationLikelihood": 0
  },
  {
    "trainNumber": "20013",
    "journeyDate": "2026-08-28",
    "travelClass": "1A",
    "quota": "GENERAL",
    "fareAmount": 1100,
    "status": "CNF",
    "confirmedSeatsRemaining": 16,
    "confirmationLikelihood": 1
  },
  {
    "trainNumber": "20014",
    "journeyDate": "2026-08-24",
    "travelClass": "SL",
    "quota": "GENERAL",
    "fareAmount": 756,
    "status": "GNWL",
    "waitlistPosition": 43,
    "confirmationLikelihood": 0.38
  },
  {
    "trainNumber": "20014",
    "journeyDate": "2026-08-26",
    "travelClass": "SL",
    "quota": "GENERAL",
    "fareAmount": 773,
    "status": "PQWL",
    "waitlistPosition": 72,
    "confirmationLikelihood": 0.05
  },
  {
    "trainNumber": "20014",
    "journeyDate": "2026-08-28",
    "travelClass": "SL",
    "quota": "GENERAL",
    "fareAmount": 790,
    "status": "RLWL",
    "waitlistPosition": 21,
    "confirmationLikelihood": 0.35
  },
  {
    "trainNumber": "20014",
    "journeyDate": "2026-08-24",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 869,
    "status": "PQWL",
    "waitlistPosition": 71,
    "confirmationLikelihood": 0.05
  },
  {
    "trainNumber": "20014",
    "journeyDate": "2026-08-26",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 886,
    "status": "RLWL",
    "waitlistPosition": 20,
    "confirmationLikelihood": 0.36
  },
  {
    "trainNumber": "20014",
    "journeyDate": "2026-08-28",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 903,
    "status": "SOLD_OUT",
    "confirmationLikelihood": 0
  },
  {
    "trainNumber": "20015",
    "journeyDate": "2026-08-24",
    "travelClass": "SL",
    "quota": "GENERAL",
    "fareAmount": 785,
    "status": "PQWL",
    "waitlistPosition": 76,
    "confirmationLikelihood": 0.05
  },
  {
    "trainNumber": "20015",
    "journeyDate": "2026-08-26",
    "travelClass": "SL",
    "quota": "GENERAL",
    "fareAmount": 802,
    "status": "RLWL",
    "waitlistPosition": 27,
    "confirmationLikelihood": 0.28
  },
  {
    "trainNumber": "20015",
    "journeyDate": "2026-08-28",
    "travelClass": "SL",
    "quota": "GENERAL",
    "fareAmount": 819,
    "status": "SOLD_OUT",
    "confirmationLikelihood": 0
  },
  {
    "trainNumber": "20015",
    "journeyDate": "2026-08-24",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 898,
    "status": "RLWL",
    "waitlistPosition": 26,
    "confirmationLikelihood": 0.29
  },
  {
    "trainNumber": "20015",
    "journeyDate": "2026-08-26",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 915,
    "status": "SOLD_OUT",
    "confirmationLikelihood": 0
  },
  {
    "trainNumber": "20015",
    "journeyDate": "2026-08-28",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 932,
    "status": "CNF",
    "confirmedSeatsRemaining": 18,
    "confirmationLikelihood": 1
  },
  {
    "trainNumber": "20015",
    "journeyDate": "2026-08-24",
    "travelClass": "2A",
    "quota": "GENERAL",
    "fareAmount": 1011,
    "status": "SOLD_OUT",
    "confirmationLikelihood": 0
  },
  {
    "trainNumber": "20015",
    "journeyDate": "2026-08-26",
    "travelClass": "2A",
    "quota": "GENERAL",
    "fareAmount": 1028,
    "status": "CNF",
    "confirmedSeatsRemaining": 17,
    "confirmationLikelihood": 1
  },
  {
    "trainNumber": "20015",
    "journeyDate": "2026-08-28",
    "travelClass": "2A",
    "quota": "GENERAL",
    "fareAmount": 1045,
    "status": "RAC",
    "racPosition": 22,
    "confirmationLikelihood": 0.75
  },
  {
    "trainNumber": "20016",
    "journeyDate": "2026-08-24",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 814,
    "status": "RLWL",
    "waitlistPosition": 33,
    "confirmationLikelihood": 0.2
  },
  {
    "trainNumber": "20016",
    "journeyDate": "2026-08-26",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 831,
    "status": "SOLD_OUT",
    "confirmationLikelihood": 0
  },
  {
    "trainNumber": "20016",
    "journeyDate": "2026-08-28",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 848,
    "status": "CNF",
    "confirmedSeatsRemaining": 19,
    "confirmationLikelihood": 1
  },
  {
    "trainNumber": "20016",
    "journeyDate": "2026-08-24",
    "travelClass": "2A",
    "quota": "GENERAL",
    "fareAmount": 927,
    "status": "SOLD_OUT",
    "confirmationLikelihood": 0
  },
  {
    "trainNumber": "20016",
    "journeyDate": "2026-08-26",
    "travelClass": "2A",
    "quota": "GENERAL",
    "fareAmount": 944,
    "status": "CNF",
    "confirmedSeatsRemaining": 18,
    "confirmationLikelihood": 1
  },
  {
    "trainNumber": "20016",
    "journeyDate": "2026-08-28",
    "travelClass": "2A",
    "quota": "GENERAL",
    "fareAmount": 961,
    "status": "RAC",
    "racPosition": 23,
    "confirmationLikelihood": 0.6
  },
  {
    "trainNumber": "20017",
    "journeyDate": "2026-08-24",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 843,
    "status": "SOLD_OUT",
    "confirmationLikelihood": 0
  },
  {
    "trainNumber": "20017",
    "journeyDate": "2026-08-26",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 860,
    "status": "CNF",
    "confirmedSeatsRemaining": 19,
    "confirmationLikelihood": 1
  },
  {
    "trainNumber": "20017",
    "journeyDate": "2026-08-28",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 877,
    "status": "RAC",
    "racPosition": 24,
    "confirmationLikelihood": 0.65
  },
  {
    "trainNumber": "20017",
    "journeyDate": "2026-08-24",
    "travelClass": "2A",
    "quota": "GENERAL",
    "fareAmount": 956,
    "status": "CNF",
    "confirmedSeatsRemaining": 18,
    "confirmationLikelihood": 1
  },
  {
    "trainNumber": "20017",
    "journeyDate": "2026-08-26",
    "travelClass": "2A",
    "quota": "GENERAL",
    "fareAmount": 973,
    "status": "RAC",
    "racPosition": 21,
    "confirmationLikelihood": 0.65
  },
  {
    "trainNumber": "20017",
    "journeyDate": "2026-08-28",
    "travelClass": "2A",
    "quota": "GENERAL",
    "fareAmount": 990,
    "status": "GNWL",
    "waitlistPosition": 54,
    "confirmationLikelihood": 0.25
  },
  {
    "trainNumber": "20017",
    "journeyDate": "2026-08-24",
    "travelClass": "1A",
    "quota": "GENERAL",
    "fareAmount": 1069,
    "status": "RAC",
    "racPosition": 18,
    "confirmationLikelihood": 0.65
  },
  {
    "trainNumber": "20017",
    "journeyDate": "2026-08-26",
    "travelClass": "1A",
    "quota": "GENERAL",
    "fareAmount": 1086,
    "status": "GNWL",
    "waitlistPosition": 53,
    "confirmationLikelihood": 0.26
  },
  {
    "trainNumber": "20017",
    "journeyDate": "2026-08-28",
    "travelClass": "1A",
    "quota": "GENERAL",
    "fareAmount": 1103,
    "status": "PQWL",
    "waitlistPosition": 8,
    "confirmationLikelihood": 0.6
  },
  {
    "trainNumber": "20018",
    "journeyDate": "2026-08-24",
    "travelClass": "SL",
    "quota": "GENERAL",
    "fareAmount": 872,
    "status": "CNF",
    "confirmedSeatsRemaining": 19,
    "confirmationLikelihood": 1
  },
  {
    "trainNumber": "20018",
    "journeyDate": "2026-08-26",
    "travelClass": "SL",
    "quota": "GENERAL",
    "fareAmount": 889,
    "status": "RAC",
    "racPosition": 22,
    "confirmationLikelihood": 0.7
  },
  {
    "trainNumber": "20018",
    "journeyDate": "2026-08-28",
    "travelClass": "SL",
    "quota": "GENERAL",
    "fareAmount": 906,
    "status": "GNWL",
    "waitlistPosition": 57,
    "confirmationLikelihood": 0.22
  },
  {
    "trainNumber": "20019",
    "journeyDate": "2026-08-24",
    "travelClass": "CC",
    "quota": "GENERAL",
    "fareAmount": 901,
    "status": "RAC",
    "racPosition": 20,
    "confirmationLikelihood": 0.75
  },
  {
    "trainNumber": "20019",
    "journeyDate": "2026-08-26",
    "travelClass": "CC",
    "quota": "GENERAL",
    "fareAmount": 918,
    "status": "GNWL",
    "waitlistPosition": 59,
    "confirmationLikelihood": 0.19
  },
  {
    "trainNumber": "20019",
    "journeyDate": "2026-08-28",
    "travelClass": "CC",
    "quota": "GENERAL",
    "fareAmount": 935,
    "status": "PQWL",
    "waitlistPosition": 18,
    "confirmationLikelihood": 0.48
  },
  {
    "trainNumber": "20020",
    "journeyDate": "2026-08-24",
    "travelClass": "SL",
    "quota": "GENERAL",
    "fareAmount": 930,
    "status": "GNWL",
    "waitlistPosition": 61,
    "confirmationLikelihood": 0.17
  },
  {
    "trainNumber": "20020",
    "journeyDate": "2026-08-26",
    "travelClass": "SL",
    "quota": "GENERAL",
    "fareAmount": 947,
    "status": "PQWL",
    "waitlistPosition": 22,
    "confirmationLikelihood": 0.44
  },
  {
    "trainNumber": "20020",
    "journeyDate": "2026-08-28",
    "travelClass": "SL",
    "quota": "GENERAL",
    "fareAmount": 964,
    "status": "RLWL",
    "waitlistPosition": 63,
    "confirmationLikelihood": 0.05
  },
  {
    "trainNumber": "20020",
    "journeyDate": "2026-08-24",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 1043,
    "status": "PQWL",
    "waitlistPosition": 21,
    "confirmationLikelihood": 0.45
  },
  {
    "trainNumber": "20020",
    "journeyDate": "2026-08-26",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 1060,
    "status": "RLWL",
    "waitlistPosition": 62,
    "confirmationLikelihood": 0.05
  },
  {
    "trainNumber": "20020",
    "journeyDate": "2026-08-28",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 1077,
    "status": "SOLD_OUT",
    "confirmationLikelihood": 0
  },
  {
    "trainNumber": "20020",
    "journeyDate": "2026-08-24",
    "travelClass": "2A",
    "quota": "GENERAL",
    "fareAmount": 1156,
    "status": "RLWL",
    "waitlistPosition": 61,
    "confirmationLikelihood": 0.05
  },
  {
    "trainNumber": "20020",
    "journeyDate": "2026-08-26",
    "travelClass": "2A",
    "quota": "GENERAL",
    "fareAmount": 1173,
    "status": "SOLD_OUT",
    "confirmationLikelihood": 0
  },
  {
    "trainNumber": "20020",
    "journeyDate": "2026-08-28",
    "travelClass": "2A",
    "quota": "GENERAL",
    "fareAmount": 1190,
    "status": "CNF",
    "confirmedSeatsRemaining": 3,
    "confirmationLikelihood": 1
  },
  {
    "trainNumber": "20020",
    "journeyDate": "2026-08-24",
    "travelClass": "1A",
    "quota": "GENERAL",
    "fareAmount": 1269,
    "status": "SOLD_OUT",
    "confirmationLikelihood": 0
  },
  {
    "trainNumber": "20020",
    "journeyDate": "2026-08-26",
    "travelClass": "1A",
    "quota": "GENERAL",
    "fareAmount": 1286,
    "status": "CNF",
    "confirmedSeatsRemaining": 2,
    "confirmationLikelihood": 1
  },
  {
    "trainNumber": "20020",
    "journeyDate": "2026-08-28",
    "travelClass": "1A",
    "quota": "GENERAL",
    "fareAmount": 1303,
    "status": "RAC",
    "racPosition": 27,
    "confirmationLikelihood": 0.6
  },
  {
    "trainNumber": "20021",
    "journeyDate": "2026-08-24",
    "travelClass": "SL",
    "quota": "GENERAL",
    "fareAmount": 959,
    "status": "PQWL",
    "waitlistPosition": 26,
    "confirmationLikelihood": 0.39
  },
  {
    "trainNumber": "20021",
    "journeyDate": "2026-08-26",
    "travelClass": "SL",
    "quota": "GENERAL",
    "fareAmount": 976,
    "status": "RLWL",
    "waitlistPosition": 69,
    "confirmationLikelihood": 0.05
  },
  {
    "trainNumber": "20021",
    "journeyDate": "2026-08-28",
    "travelClass": "SL",
    "quota": "GENERAL",
    "fareAmount": 993,
    "status": "SOLD_OUT",
    "confirmationLikelihood": 0
  },
  {
    "trainNumber": "20021",
    "journeyDate": "2026-08-24",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 1072,
    "status": "RLWL",
    "waitlistPosition": 68,
    "confirmationLikelihood": 0.05
  },
  {
    "trainNumber": "20021",
    "journeyDate": "2026-08-26",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 1089,
    "status": "SOLD_OUT",
    "confirmationLikelihood": 0
  },
  {
    "trainNumber": "20021",
    "journeyDate": "2026-08-28",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 1106,
    "status": "CNF",
    "confirmedSeatsRemaining": 4,
    "confirmationLikelihood": 1
  },
  {
    "trainNumber": "20022",
    "journeyDate": "2026-08-24",
    "travelClass": "SL",
    "quota": "GENERAL",
    "fareAmount": 988,
    "status": "RLWL",
    "waitlistPosition": 75,
    "confirmationLikelihood": 0.05
  },
  {
    "trainNumber": "20022",
    "journeyDate": "2026-08-26",
    "travelClass": "SL",
    "quota": "GENERAL",
    "fareAmount": 1005,
    "status": "SOLD_OUT",
    "confirmationLikelihood": 0
  },
  {
    "trainNumber": "20022",
    "journeyDate": "2026-08-28",
    "travelClass": "SL",
    "quota": "GENERAL",
    "fareAmount": 1022,
    "status": "CNF",
    "confirmedSeatsRemaining": 5,
    "confirmationLikelihood": 1
  },
  {
    "trainNumber": "20022",
    "journeyDate": "2026-08-24",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 1101,
    "status": "SOLD_OUT",
    "confirmationLikelihood": 0
  },
  {
    "trainNumber": "20022",
    "journeyDate": "2026-08-26",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 1118,
    "status": "CNF",
    "confirmedSeatsRemaining": 4,
    "confirmationLikelihood": 1
  },
  {
    "trainNumber": "20022",
    "journeyDate": "2026-08-28",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 1135,
    "status": "RAC",
    "racPosition": 29,
    "confirmationLikelihood": 0.7
  },
  {
    "trainNumber": "20022",
    "journeyDate": "2026-08-24",
    "travelClass": "2A",
    "quota": "GENERAL",
    "fareAmount": 1214,
    "status": "CNF",
    "confirmedSeatsRemaining": 3,
    "confirmationLikelihood": 1
  },
  {
    "trainNumber": "20022",
    "journeyDate": "2026-08-26",
    "travelClass": "2A",
    "quota": "GENERAL",
    "fareAmount": 1231,
    "status": "RAC",
    "racPosition": 26,
    "confirmationLikelihood": 0.7
  },
  {
    "trainNumber": "20022",
    "journeyDate": "2026-08-28",
    "travelClass": "2A",
    "quota": "GENERAL",
    "fareAmount": 1248,
    "status": "GNWL",
    "waitlistPosition": 69,
    "confirmationLikelihood": 0.07
  },
  {
    "trainNumber": "20023",
    "journeyDate": "2026-08-24",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 1017,
    "status": "SOLD_OUT",
    "confirmationLikelihood": 0
  },
  {
    "trainNumber": "20023",
    "journeyDate": "2026-08-26",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 1034,
    "status": "CNF",
    "confirmedSeatsRemaining": 5,
    "confirmationLikelihood": 1
  },
  {
    "trainNumber": "20023",
    "journeyDate": "2026-08-28",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 1051,
    "status": "RAC",
    "racPosition": 30,
    "confirmationLikelihood": 0.75
  },
  {
    "trainNumber": "20023",
    "journeyDate": "2026-08-24",
    "travelClass": "2A",
    "quota": "GENERAL",
    "fareAmount": 1130,
    "status": "CNF",
    "confirmedSeatsRemaining": 4,
    "confirmationLikelihood": 1
  },
  {
    "trainNumber": "20023",
    "journeyDate": "2026-08-26",
    "travelClass": "2A",
    "quota": "GENERAL",
    "fareAmount": 1147,
    "status": "RAC",
    "racPosition": 27,
    "confirmationLikelihood": 0.75
  },
  {
    "trainNumber": "20023",
    "journeyDate": "2026-08-28",
    "travelClass": "2A",
    "quota": "GENERAL",
    "fareAmount": 1164,
    "status": "GNWL",
    "waitlistPosition": 72,
    "confirmationLikelihood": 0.05
  },
  {
    "trainNumber": "20024",
    "journeyDate": "2026-08-24",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 1046,
    "status": "CNF",
    "confirmedSeatsRemaining": 5,
    "confirmationLikelihood": 1
  },
  {
    "trainNumber": "20024",
    "journeyDate": "2026-08-26",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 1063,
    "status": "RAC",
    "racPosition": 28,
    "confirmationLikelihood": 0.6
  },
  {
    "trainNumber": "20024",
    "journeyDate": "2026-08-28",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 1080,
    "status": "GNWL",
    "waitlistPosition": 75,
    "confirmationLikelihood": 0.05
  },
  {
    "trainNumber": "20024",
    "journeyDate": "2026-08-24",
    "travelClass": "2A",
    "quota": "GENERAL",
    "fareAmount": 1159,
    "status": "RAC",
    "racPosition": 25,
    "confirmationLikelihood": 0.6
  },
  {
    "trainNumber": "20024",
    "journeyDate": "2026-08-26",
    "travelClass": "2A",
    "quota": "GENERAL",
    "fareAmount": 1176,
    "status": "GNWL",
    "waitlistPosition": 74,
    "confirmationLikelihood": 0.05
  },
  {
    "trainNumber": "20024",
    "journeyDate": "2026-08-28",
    "travelClass": "2A",
    "quota": "GENERAL",
    "fareAmount": 1193,
    "status": "PQWL",
    "waitlistPosition": 43,
    "confirmationLikelihood": 0.18
  },
  {
    "trainNumber": "20024",
    "journeyDate": "2026-08-24",
    "travelClass": "1A",
    "quota": "GENERAL",
    "fareAmount": 1272,
    "status": "GNWL",
    "waitlistPosition": 73,
    "confirmationLikelihood": 0.05
  },
  {
    "trainNumber": "20024",
    "journeyDate": "2026-08-26",
    "travelClass": "1A",
    "quota": "GENERAL",
    "fareAmount": 1289,
    "status": "PQWL",
    "waitlistPosition": 42,
    "confirmationLikelihood": 0.2
  },
  {
    "trainNumber": "20024",
    "journeyDate": "2026-08-28",
    "travelClass": "1A",
    "quota": "GENERAL",
    "fareAmount": 1306,
    "status": "RLWL",
    "waitlistPosition": 11,
    "confirmationLikelihood": 0.47
  },
  {
    "trainNumber": "20025",
    "journeyDate": "2026-08-24",
    "travelClass": "SL",
    "quota": "GENERAL",
    "fareAmount": 1075,
    "status": "RAC",
    "racPosition": 26,
    "confirmationLikelihood": 0.65
  },
  {
    "trainNumber": "20025",
    "journeyDate": "2026-08-26",
    "travelClass": "SL",
    "quota": "GENERAL",
    "fareAmount": 1092,
    "status": "GNWL",
    "waitlistPosition": 77,
    "confirmationLikelihood": 0.05
  },
  {
    "trainNumber": "20025",
    "journeyDate": "2026-08-28",
    "travelClass": "SL",
    "quota": "GENERAL",
    "fareAmount": 1109,
    "status": "PQWL",
    "waitlistPosition": 48,
    "confirmationLikelihood": 0.12
  },
  {
    "trainNumber": "20026",
    "journeyDate": "2026-08-24",
    "travelClass": "CC",
    "quota": "GENERAL",
    "fareAmount": 1104,
    "status": "GNWL",
    "waitlistPosition": 79,
    "confirmationLikelihood": 0.05
  },
  {
    "trainNumber": "20026",
    "journeyDate": "2026-08-26",
    "travelClass": "CC",
    "quota": "GENERAL",
    "fareAmount": 1121,
    "status": "PQWL",
    "waitlistPosition": 52,
    "confirmationLikelihood": 0.08
  },
  {
    "trainNumber": "20026",
    "journeyDate": "2026-08-28",
    "travelClass": "CC",
    "quota": "GENERAL",
    "fareAmount": 1138,
    "status": "RLWL",
    "waitlistPosition": 25,
    "confirmationLikelihood": 0.3
  },
  {
    "trainNumber": "20027",
    "journeyDate": "2026-08-24",
    "travelClass": "SL",
    "quota": "GENERAL",
    "fareAmount": 1133,
    "status": "PQWL",
    "waitlistPosition": 56,
    "confirmationLikelihood": 0.05
  },
  {
    "trainNumber": "20027",
    "journeyDate": "2026-08-26",
    "travelClass": "SL",
    "quota": "GENERAL",
    "fareAmount": 1150,
    "status": "RLWL",
    "waitlistPosition": 31,
    "confirmationLikelihood": 0.23
  },
  {
    "trainNumber": "20027",
    "journeyDate": "2026-08-28",
    "travelClass": "SL",
    "quota": "GENERAL",
    "fareAmount": 1167,
    "status": "SOLD_OUT",
    "confirmationLikelihood": 0
  },
  {
    "trainNumber": "20027",
    "journeyDate": "2026-08-24",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 1246,
    "status": "RLWL",
    "waitlistPosition": 30,
    "confirmationLikelihood": 0.24
  },
  {
    "trainNumber": "20027",
    "journeyDate": "2026-08-26",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 1263,
    "status": "SOLD_OUT",
    "confirmationLikelihood": 0
  },
  {
    "trainNumber": "20027",
    "journeyDate": "2026-08-28",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 1280,
    "status": "CNF",
    "confirmedSeatsRemaining": 10,
    "confirmationLikelihood": 1
  },
  {
    "trainNumber": "20027",
    "journeyDate": "2026-08-24",
    "travelClass": "2A",
    "quota": "GENERAL",
    "fareAmount": 1359,
    "status": "SOLD_OUT",
    "confirmationLikelihood": 0
  },
  {
    "trainNumber": "20027",
    "journeyDate": "2026-08-26",
    "travelClass": "2A",
    "quota": "GENERAL",
    "fareAmount": 1376,
    "status": "CNF",
    "confirmedSeatsRemaining": 9,
    "confirmationLikelihood": 1
  },
  {
    "trainNumber": "20027",
    "journeyDate": "2026-08-28",
    "travelClass": "2A",
    "quota": "GENERAL",
    "fareAmount": 1393,
    "status": "RAC",
    "racPosition": 4,
    "confirmationLikelihood": 0.75
  },
  {
    "trainNumber": "20027",
    "journeyDate": "2026-08-24",
    "travelClass": "1A",
    "quota": "GENERAL",
    "fareAmount": 1472,
    "status": "CNF",
    "confirmedSeatsRemaining": 8,
    "confirmationLikelihood": 1
  },
  {
    "trainNumber": "20027",
    "journeyDate": "2026-08-26",
    "travelClass": "1A",
    "quota": "GENERAL",
    "fareAmount": 1489,
    "status": "RAC",
    "racPosition": 1,
    "confirmationLikelihood": 0.75
  },
  {
    "trainNumber": "20027",
    "journeyDate": "2026-08-28",
    "travelClass": "1A",
    "quota": "GENERAL",
    "fareAmount": 1506,
    "status": "GNWL",
    "waitlistPosition": 4,
    "confirmationLikelihood": 0.85
  },
  {
    "trainNumber": "20028",
    "journeyDate": "2026-08-24",
    "travelClass": "SL",
    "quota": "GENERAL",
    "fareAmount": 1162,
    "status": "RLWL",
    "waitlistPosition": 37,
    "confirmationLikelihood": 0.16
  },
  {
    "trainNumber": "20028",
    "journeyDate": "2026-08-26",
    "travelClass": "SL",
    "quota": "GENERAL",
    "fareAmount": 1179,
    "status": "SOLD_OUT",
    "confirmationLikelihood": 0
  },
  {
    "trainNumber": "20028",
    "journeyDate": "2026-08-28",
    "travelClass": "SL",
    "quota": "GENERAL",
    "fareAmount": 1196,
    "status": "CNF",
    "confirmedSeatsRemaining": 11,
    "confirmationLikelihood": 1
  },
  {
    "trainNumber": "20028",
    "journeyDate": "2026-08-24",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 1275,
    "status": "SOLD_OUT",
    "confirmationLikelihood": 0
  },
  {
    "trainNumber": "20028",
    "journeyDate": "2026-08-26",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 1292,
    "status": "CNF",
    "confirmedSeatsRemaining": 10,
    "confirmationLikelihood": 1
  },
  {
    "trainNumber": "20028",
    "journeyDate": "2026-08-28",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 1309,
    "status": "RAC",
    "racPosition": 5,
    "confirmationLikelihood": 0.6
  },
  {
    "trainNumber": "20029",
    "journeyDate": "2026-08-24",
    "travelClass": "SL",
    "quota": "GENERAL",
    "fareAmount": 1191,
    "status": "SOLD_OUT",
    "confirmationLikelihood": 0
  },
  {
    "trainNumber": "20029",
    "journeyDate": "2026-08-26",
    "travelClass": "SL",
    "quota": "GENERAL",
    "fareAmount": 1208,
    "status": "CNF",
    "confirmedSeatsRemaining": 11,
    "confirmationLikelihood": 1
  },
  {
    "trainNumber": "20029",
    "journeyDate": "2026-08-28",
    "travelClass": "SL",
    "quota": "GENERAL",
    "fareAmount": 1225,
    "status": "RAC",
    "racPosition": 6,
    "confirmationLikelihood": 0.65
  },
  {
    "trainNumber": "20029",
    "journeyDate": "2026-08-24",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 1304,
    "status": "CNF",
    "confirmedSeatsRemaining": 10,
    "confirmationLikelihood": 1
  },
  {
    "trainNumber": "20029",
    "journeyDate": "2026-08-26",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 1321,
    "status": "RAC",
    "racPosition": 3,
    "confirmationLikelihood": 0.65
  },
  {
    "trainNumber": "20029",
    "journeyDate": "2026-08-28",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 1338,
    "status": "GNWL",
    "waitlistPosition": 10,
    "confirmationLikelihood": 0.78
  },
  {
    "trainNumber": "20029",
    "journeyDate": "2026-08-24",
    "travelClass": "2A",
    "quota": "GENERAL",
    "fareAmount": 1417,
    "status": "RAC",
    "racPosition": 30,
    "confirmationLikelihood": 0.65
  },
  {
    "trainNumber": "20029",
    "journeyDate": "2026-08-26",
    "travelClass": "2A",
    "quota": "GENERAL",
    "fareAmount": 1434,
    "status": "GNWL",
    "waitlistPosition": 9,
    "confirmationLikelihood": 0.79
  },
  {
    "trainNumber": "20029",
    "journeyDate": "2026-08-28",
    "travelClass": "2A",
    "quota": "GENERAL",
    "fareAmount": 1451,
    "status": "PQWL",
    "waitlistPosition": 68,
    "confirmationLikelihood": 0.05
  },
  {
    "trainNumber": "20030",
    "journeyDate": "2026-08-24",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 1220,
    "status": "CNF",
    "confirmedSeatsRemaining": 11,
    "confirmationLikelihood": 1
  },
  {
    "trainNumber": "20030",
    "journeyDate": "2026-08-26",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 1237,
    "status": "RAC",
    "racPosition": 4,
    "confirmationLikelihood": 0.7
  },
  {
    "trainNumber": "20030",
    "journeyDate": "2026-08-28",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 1254,
    "status": "GNWL",
    "waitlistPosition": 13,
    "confirmationLikelihood": 0.74
  },
  {
    "trainNumber": "20030",
    "journeyDate": "2026-08-24",
    "travelClass": "2A",
    "quota": "GENERAL",
    "fareAmount": 1333,
    "status": "RAC",
    "racPosition": 1,
    "confirmationLikelihood": 0.7
  },
  {
    "trainNumber": "20030",
    "journeyDate": "2026-08-26",
    "travelClass": "2A",
    "quota": "GENERAL",
    "fareAmount": 1350,
    "status": "GNWL",
    "waitlistPosition": 12,
    "confirmationLikelihood": 0.76
  },
  {
    "trainNumber": "20030",
    "journeyDate": "2026-08-28",
    "travelClass": "2A",
    "quota": "GENERAL",
    "fareAmount": 1367,
    "status": "PQWL",
    "waitlistPosition": 73,
    "confirmationLikelihood": 0.05
  },
  {
    "trainNumber": "20031",
    "journeyDate": "2026-08-24",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 1249,
    "status": "RAC",
    "racPosition": 2,
    "confirmationLikelihood": 0.75
  },
  {
    "trainNumber": "20031",
    "journeyDate": "2026-08-26",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 1266,
    "status": "GNWL",
    "waitlistPosition": 15,
    "confirmationLikelihood": 0.72
  },
  {
    "trainNumber": "20031",
    "journeyDate": "2026-08-28",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 1283,
    "status": "PQWL",
    "waitlistPosition": 78,
    "confirmationLikelihood": 0.05
  },
  {
    "trainNumber": "20031",
    "journeyDate": "2026-08-24",
    "travelClass": "2A",
    "quota": "GENERAL",
    "fareAmount": 1362,
    "status": "GNWL",
    "waitlistPosition": 14,
    "confirmationLikelihood": 0.73
  },
  {
    "trainNumber": "20031",
    "journeyDate": "2026-08-26",
    "travelClass": "2A",
    "quota": "GENERAL",
    "fareAmount": 1379,
    "status": "PQWL",
    "waitlistPosition": 77,
    "confirmationLikelihood": 0.05
  },
  {
    "trainNumber": "20031",
    "journeyDate": "2026-08-28",
    "travelClass": "2A",
    "quota": "GENERAL",
    "fareAmount": 1396,
    "status": "RLWL",
    "waitlistPosition": 60,
    "confirmationLikelihood": 0.05
  },
  {
    "trainNumber": "20031",
    "journeyDate": "2026-08-24",
    "travelClass": "1A",
    "quota": "GENERAL",
    "fareAmount": 1475,
    "status": "PQWL",
    "waitlistPosition": 76,
    "confirmationLikelihood": 0.05
  },
  {
    "trainNumber": "20031",
    "journeyDate": "2026-08-26",
    "travelClass": "1A",
    "quota": "GENERAL",
    "fareAmount": 1492,
    "status": "RLWL",
    "waitlistPosition": 59,
    "confirmationLikelihood": 0.05
  },
  {
    "trainNumber": "20031",
    "journeyDate": "2026-08-28",
    "travelClass": "1A",
    "quota": "GENERAL",
    "fareAmount": 1509,
    "status": "SOLD_OUT",
    "confirmationLikelihood": 0
  },
  {
    "trainNumber": "20032",
    "journeyDate": "2026-08-24",
    "travelClass": "SL",
    "quota": "GENERAL",
    "fareAmount": 1278,
    "status": "GNWL",
    "waitlistPosition": 17,
    "confirmationLikelihood": 0.7
  },
  {
    "trainNumber": "20032",
    "journeyDate": "2026-08-26",
    "travelClass": "SL",
    "quota": "GENERAL",
    "fareAmount": 1295,
    "status": "PQWL",
    "waitlistPosition": 2,
    "confirmationLikelihood": 0.68
  },
  {
    "trainNumber": "20032",
    "journeyDate": "2026-08-28",
    "travelClass": "SL",
    "quota": "GENERAL",
    "fareAmount": 1312,
    "status": "RLWL",
    "waitlistPosition": 67,
    "confirmationLikelihood": 0.05
  },
  {
    "trainNumber": "20033",
    "journeyDate": "2026-08-24",
    "travelClass": "CC",
    "quota": "GENERAL",
    "fareAmount": 1307,
    "status": "PQWL",
    "waitlistPosition": 6,
    "confirmationLikelihood": 0.63
  },
  {
    "trainNumber": "20033",
    "journeyDate": "2026-08-26",
    "travelClass": "CC",
    "quota": "GENERAL",
    "fareAmount": 1324,
    "status": "RLWL",
    "waitlistPosition": 73,
    "confirmationLikelihood": 0.05
  },
  {
    "trainNumber": "20033",
    "journeyDate": "2026-08-28",
    "travelClass": "CC",
    "quota": "GENERAL",
    "fareAmount": 1341,
    "status": "SOLD_OUT",
    "confirmationLikelihood": 0
  },
  {
    "trainNumber": "20034",
    "journeyDate": "2026-08-24",
    "travelClass": "SL",
    "quota": "GENERAL",
    "fareAmount": 1336,
    "status": "RLWL",
    "waitlistPosition": 79,
    "confirmationLikelihood": 0.05
  },
  {
    "trainNumber": "20034",
    "journeyDate": "2026-08-26",
    "travelClass": "SL",
    "quota": "GENERAL",
    "fareAmount": 1353,
    "status": "SOLD_OUT",
    "confirmationLikelihood": 0
  },
  {
    "trainNumber": "20034",
    "journeyDate": "2026-08-28",
    "travelClass": "SL",
    "quota": "GENERAL",
    "fareAmount": 1370,
    "status": "CNF",
    "confirmedSeatsRemaining": 17,
    "confirmationLikelihood": 1
  },
  {
    "trainNumber": "20034",
    "journeyDate": "2026-08-24",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 1449,
    "status": "SOLD_OUT",
    "confirmationLikelihood": 0
  },
  {
    "trainNumber": "20034",
    "journeyDate": "2026-08-26",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 1466,
    "status": "CNF",
    "confirmedSeatsRemaining": 16,
    "confirmationLikelihood": 1
  },
  {
    "trainNumber": "20034",
    "journeyDate": "2026-08-28",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 1483,
    "status": "RAC",
    "racPosition": 11,
    "confirmationLikelihood": 0.7
  },
  {
    "trainNumber": "20034",
    "journeyDate": "2026-08-24",
    "travelClass": "2A",
    "quota": "GENERAL",
    "fareAmount": 1562,
    "status": "CNF",
    "confirmedSeatsRemaining": 15,
    "confirmationLikelihood": 1
  },
  {
    "trainNumber": "20034",
    "journeyDate": "2026-08-26",
    "travelClass": "2A",
    "quota": "GENERAL",
    "fareAmount": 1579,
    "status": "RAC",
    "racPosition": 8,
    "confirmationLikelihood": 0.7
  },
  {
    "trainNumber": "20034",
    "journeyDate": "2026-08-28",
    "travelClass": "2A",
    "quota": "GENERAL",
    "fareAmount": 1596,
    "status": "GNWL",
    "waitlistPosition": 25,
    "confirmationLikelihood": 0.6
  },
  {
    "trainNumber": "20034",
    "journeyDate": "2026-08-24",
    "travelClass": "1A",
    "quota": "GENERAL",
    "fareAmount": 1675,
    "status": "RAC",
    "racPosition": 5,
    "confirmationLikelihood": 0.7
  },
  {
    "trainNumber": "20034",
    "journeyDate": "2026-08-26",
    "travelClass": "1A",
    "quota": "GENERAL",
    "fareAmount": 1692,
    "status": "GNWL",
    "waitlistPosition": 24,
    "confirmationLikelihood": 0.61
  },
  {
    "trainNumber": "20034",
    "journeyDate": "2026-08-28",
    "travelClass": "1A",
    "quota": "GENERAL",
    "fareAmount": 1709,
    "status": "PQWL",
    "waitlistPosition": 13,
    "confirmationLikelihood": 0.54
  },
  {
    "trainNumber": "20035",
    "journeyDate": "2026-08-24",
    "travelClass": "SL",
    "quota": "GENERAL",
    "fareAmount": 1365,
    "status": "SOLD_OUT",
    "confirmationLikelihood": 0
  },
  {
    "trainNumber": "20035",
    "journeyDate": "2026-08-26",
    "travelClass": "SL",
    "quota": "GENERAL",
    "fareAmount": 1382,
    "status": "CNF",
    "confirmedSeatsRemaining": 17,
    "confirmationLikelihood": 1
  },
  {
    "trainNumber": "20035",
    "journeyDate": "2026-08-28",
    "travelClass": "SL",
    "quota": "GENERAL",
    "fareAmount": 1399,
    "status": "RAC",
    "racPosition": 12,
    "confirmationLikelihood": 0.75
  },
  {
    "trainNumber": "20035",
    "journeyDate": "2026-08-24",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 1478,
    "status": "CNF",
    "confirmedSeatsRemaining": 16,
    "confirmationLikelihood": 1
  },
  {
    "trainNumber": "20035",
    "journeyDate": "2026-08-26",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 1495,
    "status": "RAC",
    "racPosition": 9,
    "confirmationLikelihood": 0.75
  },
  {
    "trainNumber": "20035",
    "journeyDate": "2026-08-28",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 1512,
    "status": "GNWL",
    "waitlistPosition": 28,
    "confirmationLikelihood": 0.56
  },
  {
    "trainNumber": "20036",
    "journeyDate": "2026-08-24",
    "travelClass": "SL",
    "quota": "GENERAL",
    "fareAmount": 1394,
    "status": "CNF",
    "confirmedSeatsRemaining": 17,
    "confirmationLikelihood": 1
  },
  {
    "trainNumber": "20036",
    "journeyDate": "2026-08-26",
    "travelClass": "SL",
    "quota": "GENERAL",
    "fareAmount": 1411,
    "status": "RAC",
    "racPosition": 10,
    "confirmationLikelihood": 0.6
  },
  {
    "trainNumber": "20036",
    "journeyDate": "2026-08-28",
    "travelClass": "SL",
    "quota": "GENERAL",
    "fareAmount": 1428,
    "status": "GNWL",
    "waitlistPosition": 31,
    "confirmationLikelihood": 0.53
  },
  {
    "trainNumber": "20036",
    "journeyDate": "2026-08-24",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 1507,
    "status": "RAC",
    "racPosition": 7,
    "confirmationLikelihood": 0.6
  },
  {
    "trainNumber": "20036",
    "journeyDate": "2026-08-26",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 1524,
    "status": "GNWL",
    "waitlistPosition": 30,
    "confirmationLikelihood": 0.54
  },
  {
    "trainNumber": "20036",
    "journeyDate": "2026-08-28",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 1541,
    "status": "PQWL",
    "waitlistPosition": 23,
    "confirmationLikelihood": 0.42
  },
  {
    "trainNumber": "20036",
    "journeyDate": "2026-08-24",
    "travelClass": "2A",
    "quota": "GENERAL",
    "fareAmount": 1620,
    "status": "GNWL",
    "waitlistPosition": 29,
    "confirmationLikelihood": 0.55
  },
  {
    "trainNumber": "20036",
    "journeyDate": "2026-08-26",
    "travelClass": "2A",
    "quota": "GENERAL",
    "fareAmount": 1637,
    "status": "PQWL",
    "waitlistPosition": 22,
    "confirmationLikelihood": 0.44
  },
  {
    "trainNumber": "20036",
    "journeyDate": "2026-08-28",
    "travelClass": "2A",
    "quota": "GENERAL",
    "fareAmount": 1654,
    "status": "RLWL",
    "waitlistPosition": 15,
    "confirmationLikelihood": 0.42
  },
  {
    "trainNumber": "20037",
    "journeyDate": "2026-08-24",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 1423,
    "status": "RAC",
    "racPosition": 8,
    "confirmationLikelihood": 0.65
  },
  {
    "trainNumber": "20037",
    "journeyDate": "2026-08-26",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 1440,
    "status": "GNWL",
    "waitlistPosition": 33,
    "confirmationLikelihood": 0.5
  },
  {
    "trainNumber": "20037",
    "journeyDate": "2026-08-28",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 1457,
    "status": "PQWL",
    "waitlistPosition": 28,
    "confirmationLikelihood": 0.36
  },
  {
    "trainNumber": "20037",
    "journeyDate": "2026-08-24",
    "travelClass": "2A",
    "quota": "GENERAL",
    "fareAmount": 1536,
    "status": "GNWL",
    "waitlistPosition": 32,
    "confirmationLikelihood": 0.52
  },
  {
    "trainNumber": "20037",
    "journeyDate": "2026-08-26",
    "travelClass": "2A",
    "quota": "GENERAL",
    "fareAmount": 1553,
    "status": "PQWL",
    "waitlistPosition": 27,
    "confirmationLikelihood": 0.38
  },
  {
    "trainNumber": "20037",
    "journeyDate": "2026-08-28",
    "travelClass": "2A",
    "quota": "GENERAL",
    "fareAmount": 1570,
    "status": "RLWL",
    "waitlistPosition": 22,
    "confirmationLikelihood": 0.34
  },
  {
    "trainNumber": "20038",
    "journeyDate": "2026-08-24",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 1452,
    "status": "GNWL",
    "waitlistPosition": 35,
    "confirmationLikelihood": 0.48
  },
  {
    "trainNumber": "20038",
    "journeyDate": "2026-08-26",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 1469,
    "status": "PQWL",
    "waitlistPosition": 32,
    "confirmationLikelihood": 0.32
  },
  {
    "trainNumber": "20038",
    "journeyDate": "2026-08-28",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 1486,
    "status": "RLWL",
    "waitlistPosition": 29,
    "confirmationLikelihood": 0.25
  },
  {
    "trainNumber": "20038",
    "journeyDate": "2026-08-24",
    "travelClass": "2A",
    "quota": "GENERAL",
    "fareAmount": 1565,
    "status": "PQWL",
    "waitlistPosition": 31,
    "confirmationLikelihood": 0.33
  },
  {
    "trainNumber": "20038",
    "journeyDate": "2026-08-26",
    "travelClass": "2A",
    "quota": "GENERAL",
    "fareAmount": 1582,
    "status": "RLWL",
    "waitlistPosition": 28,
    "confirmationLikelihood": 0.26
  },
  {
    "trainNumber": "20038",
    "journeyDate": "2026-08-28",
    "travelClass": "2A",
    "quota": "GENERAL",
    "fareAmount": 1599,
    "status": "SOLD_OUT",
    "confirmationLikelihood": 0
  },
  {
    "trainNumber": "20038",
    "journeyDate": "2026-08-24",
    "travelClass": "1A",
    "quota": "GENERAL",
    "fareAmount": 1678,
    "status": "RLWL",
    "waitlistPosition": 27,
    "confirmationLikelihood": 0.28
  },
  {
    "trainNumber": "20038",
    "journeyDate": "2026-08-26",
    "travelClass": "1A",
    "quota": "GENERAL",
    "fareAmount": 1695,
    "status": "SOLD_OUT",
    "confirmationLikelihood": 0
  },
  {
    "trainNumber": "20038",
    "journeyDate": "2026-08-28",
    "travelClass": "1A",
    "quota": "GENERAL",
    "fareAmount": 1712,
    "status": "CNF",
    "confirmedSeatsRemaining": 1,
    "confirmationLikelihood": 1
  },
  {
    "trainNumber": "20039",
    "journeyDate": "2026-08-24",
    "travelClass": "SL",
    "quota": "GENERAL",
    "fareAmount": 1481,
    "status": "PQWL",
    "waitlistPosition": 36,
    "confirmationLikelihood": 0.27
  },
  {
    "trainNumber": "20039",
    "journeyDate": "2026-08-26",
    "travelClass": "SL",
    "quota": "GENERAL",
    "fareAmount": 1498,
    "status": "RLWL",
    "waitlistPosition": 35,
    "confirmationLikelihood": 0.18
  },
  {
    "trainNumber": "20039",
    "journeyDate": "2026-08-28",
    "travelClass": "SL",
    "quota": "GENERAL",
    "fareAmount": 1515,
    "status": "SOLD_OUT",
    "confirmationLikelihood": 0
  },
  {
    "trainNumber": "20040",
    "journeyDate": "2026-08-24",
    "travelClass": "CC",
    "quota": "GENERAL",
    "fareAmount": 1510,
    "status": "RLWL",
    "waitlistPosition": 41,
    "confirmationLikelihood": 0.11
  },
  {
    "trainNumber": "20040",
    "journeyDate": "2026-08-26",
    "travelClass": "CC",
    "quota": "GENERAL",
    "fareAmount": 1527,
    "status": "SOLD_OUT",
    "confirmationLikelihood": 0
  },
  {
    "trainNumber": "20040",
    "journeyDate": "2026-08-28",
    "travelClass": "CC",
    "quota": "GENERAL",
    "fareAmount": 1544,
    "status": "CNF",
    "confirmedSeatsRemaining": 3,
    "confirmationLikelihood": 1
  },
  {
    "trainNumber": "20041",
    "journeyDate": "2026-08-24",
    "travelClass": "SL",
    "quota": "GENERAL",
    "fareAmount": 1539,
    "status": "SOLD_OUT",
    "confirmationLikelihood": 0
  },
  {
    "trainNumber": "20041",
    "journeyDate": "2026-08-26",
    "travelClass": "SL",
    "quota": "GENERAL",
    "fareAmount": 1556,
    "status": "CNF",
    "confirmedSeatsRemaining": 3,
    "confirmationLikelihood": 1
  },
  {
    "trainNumber": "20041",
    "journeyDate": "2026-08-28",
    "travelClass": "SL",
    "quota": "GENERAL",
    "fareAmount": 1573,
    "status": "RAC",
    "racPosition": 18,
    "confirmationLikelihood": 0.65
  },
  {
    "trainNumber": "20041",
    "journeyDate": "2026-08-24",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 1652,
    "status": "CNF",
    "confirmedSeatsRemaining": 2,
    "confirmationLikelihood": 1
  },
  {
    "trainNumber": "20041",
    "journeyDate": "2026-08-26",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 1669,
    "status": "RAC",
    "racPosition": 15,
    "confirmationLikelihood": 0.65
  },
  {
    "trainNumber": "20041",
    "journeyDate": "2026-08-28",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 1686,
    "status": "GNWL",
    "waitlistPosition": 46,
    "confirmationLikelihood": 0.35
  },
  {
    "trainNumber": "20041",
    "journeyDate": "2026-08-24",
    "travelClass": "2A",
    "quota": "GENERAL",
    "fareAmount": 1765,
    "status": "RAC",
    "racPosition": 12,
    "confirmationLikelihood": 0.65
  },
  {
    "trainNumber": "20041",
    "journeyDate": "2026-08-26",
    "travelClass": "2A",
    "quota": "GENERAL",
    "fareAmount": 1782,
    "status": "GNWL",
    "waitlistPosition": 45,
    "confirmationLikelihood": 0.36
  },
  {
    "trainNumber": "20041",
    "journeyDate": "2026-08-28",
    "travelClass": "2A",
    "quota": "GENERAL",
    "fareAmount": 1799,
    "status": "PQWL",
    "waitlistPosition": 48,
    "confirmationLikelihood": 0.12
  },
  {
    "trainNumber": "20041",
    "journeyDate": "2026-08-24",
    "travelClass": "1A",
    "quota": "GENERAL",
    "fareAmount": 1878,
    "status": "GNWL",
    "waitlistPosition": 44,
    "confirmationLikelihood": 0.37
  },
  {
    "trainNumber": "20041",
    "journeyDate": "2026-08-26",
    "travelClass": "1A",
    "quota": "GENERAL",
    "fareAmount": 1895,
    "status": "PQWL",
    "waitlistPosition": 47,
    "confirmationLikelihood": 0.14
  },
  {
    "trainNumber": "20041",
    "journeyDate": "2026-08-28",
    "travelClass": "1A",
    "quota": "GENERAL",
    "fareAmount": 1912,
    "status": "RLWL",
    "waitlistPosition": 50,
    "confirmationLikelihood": 0.05
  },
  {
    "trainNumber": "20042",
    "journeyDate": "2026-08-24",
    "travelClass": "SL",
    "quota": "GENERAL",
    "fareAmount": 1568,
    "status": "CNF",
    "confirmedSeatsRemaining": 3,
    "confirmationLikelihood": 1
  },
  {
    "trainNumber": "20042",
    "journeyDate": "2026-08-26",
    "travelClass": "SL",
    "quota": "GENERAL",
    "fareAmount": 1585,
    "status": "RAC",
    "racPosition": 16,
    "confirmationLikelihood": 0.7
  },
  {
    "trainNumber": "20042",
    "journeyDate": "2026-08-28",
    "travelClass": "SL",
    "quota": "GENERAL",
    "fareAmount": 1602,
    "status": "GNWL",
    "waitlistPosition": 49,
    "confirmationLikelihood": 0.31
  },
  {
    "trainNumber": "20042",
    "journeyDate": "2026-08-24",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 1681,
    "status": "RAC",
    "racPosition": 13,
    "confirmationLikelihood": 0.7
  },
  {
    "trainNumber": "20042",
    "journeyDate": "2026-08-26",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 1698,
    "status": "GNWL",
    "waitlistPosition": 48,
    "confirmationLikelihood": 0.32
  },
  {
    "trainNumber": "20042",
    "journeyDate": "2026-08-28",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 1715,
    "status": "PQWL",
    "waitlistPosition": 53,
    "confirmationLikelihood": 0.06
  },
  {
    "trainNumber": "20043",
    "journeyDate": "2026-08-24",
    "travelClass": "SL",
    "quota": "GENERAL",
    "fareAmount": 1597,
    "status": "RAC",
    "racPosition": 14,
    "confirmationLikelihood": 0.75
  },
  {
    "trainNumber": "20043",
    "journeyDate": "2026-08-26",
    "travelClass": "SL",
    "quota": "GENERAL",
    "fareAmount": 1614,
    "status": "GNWL",
    "waitlistPosition": 51,
    "confirmationLikelihood": 0.29
  },
  {
    "trainNumber": "20043",
    "journeyDate": "2026-08-28",
    "travelClass": "SL",
    "quota": "GENERAL",
    "fareAmount": 1631,
    "status": "PQWL",
    "waitlistPosition": 58,
    "confirmationLikelihood": 0.05
  },
  {
    "trainNumber": "20043",
    "journeyDate": "2026-08-24",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 1710,
    "status": "GNWL",
    "waitlistPosition": 50,
    "confirmationLikelihood": 0.3
  },
  {
    "trainNumber": "20043",
    "journeyDate": "2026-08-26",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 1727,
    "status": "PQWL",
    "waitlistPosition": 57,
    "confirmationLikelihood": 0.05
  },
  {
    "trainNumber": "20043",
    "journeyDate": "2026-08-28",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 1744,
    "status": "RLWL",
    "waitlistPosition": 64,
    "confirmationLikelihood": 0.05
  },
  {
    "trainNumber": "20043",
    "journeyDate": "2026-08-24",
    "travelClass": "2A",
    "quota": "GENERAL",
    "fareAmount": 1823,
    "status": "PQWL",
    "waitlistPosition": 56,
    "confirmationLikelihood": 0.05
  },
  {
    "trainNumber": "20043",
    "journeyDate": "2026-08-26",
    "travelClass": "2A",
    "quota": "GENERAL",
    "fareAmount": 1840,
    "status": "RLWL",
    "waitlistPosition": 63,
    "confirmationLikelihood": 0.05
  },
  {
    "trainNumber": "20043",
    "journeyDate": "2026-08-28",
    "travelClass": "2A",
    "quota": "GENERAL",
    "fareAmount": 1857,
    "status": "SOLD_OUT",
    "confirmationLikelihood": 0
  },
  {
    "trainNumber": "20044",
    "journeyDate": "2026-08-24",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 1626,
    "status": "GNWL",
    "waitlistPosition": 53,
    "confirmationLikelihood": 0.26
  },
  {
    "trainNumber": "20044",
    "journeyDate": "2026-08-26",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 1643,
    "status": "PQWL",
    "waitlistPosition": 62,
    "confirmationLikelihood": 0.05
  },
  {
    "trainNumber": "20044",
    "journeyDate": "2026-08-28",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 1660,
    "status": "RLWL",
    "waitlistPosition": 71,
    "confirmationLikelihood": 0.05
  },
  {
    "trainNumber": "20044",
    "journeyDate": "2026-08-24",
    "travelClass": "2A",
    "quota": "GENERAL",
    "fareAmount": 1739,
    "status": "PQWL",
    "waitlistPosition": 61,
    "confirmationLikelihood": 0.05
  },
  {
    "trainNumber": "20044",
    "journeyDate": "2026-08-26",
    "travelClass": "2A",
    "quota": "GENERAL",
    "fareAmount": 1756,
    "status": "RLWL",
    "waitlistPosition": 70,
    "confirmationLikelihood": 0.05
  },
  {
    "trainNumber": "20044",
    "journeyDate": "2026-08-28",
    "travelClass": "2A",
    "quota": "GENERAL",
    "fareAmount": 1773,
    "status": "SOLD_OUT",
    "confirmationLikelihood": 0
  },
  {
    "trainNumber": "20045",
    "journeyDate": "2026-08-24",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 1655,
    "status": "PQWL",
    "waitlistPosition": 66,
    "confirmationLikelihood": 0.05
  },
  {
    "trainNumber": "20045",
    "journeyDate": "2026-08-26",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 1672,
    "status": "RLWL",
    "waitlistPosition": 77,
    "confirmationLikelihood": 0.05
  },
  {
    "trainNumber": "20045",
    "journeyDate": "2026-08-28",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 1689,
    "status": "SOLD_OUT",
    "confirmationLikelihood": 0
  },
  {
    "trainNumber": "20045",
    "journeyDate": "2026-08-24",
    "travelClass": "2A",
    "quota": "GENERAL",
    "fareAmount": 1768,
    "status": "RLWL",
    "waitlistPosition": 76,
    "confirmationLikelihood": 0.05
  },
  {
    "trainNumber": "20045",
    "journeyDate": "2026-08-26",
    "travelClass": "2A",
    "quota": "GENERAL",
    "fareAmount": 1785,
    "status": "SOLD_OUT",
    "confirmationLikelihood": 0
  },
  {
    "trainNumber": "20045",
    "journeyDate": "2026-08-28",
    "travelClass": "2A",
    "quota": "GENERAL",
    "fareAmount": 1802,
    "status": "CNF",
    "confirmedSeatsRemaining": 8,
    "confirmationLikelihood": 1
  },
  {
    "trainNumber": "20045",
    "journeyDate": "2026-08-24",
    "travelClass": "1A",
    "quota": "GENERAL",
    "fareAmount": 1881,
    "status": "SOLD_OUT",
    "confirmationLikelihood": 0
  },
  {
    "trainNumber": "20045",
    "journeyDate": "2026-08-26",
    "travelClass": "1A",
    "quota": "GENERAL",
    "fareAmount": 1898,
    "status": "CNF",
    "confirmedSeatsRemaining": 7,
    "confirmationLikelihood": 1
  },
  {
    "trainNumber": "20045",
    "journeyDate": "2026-08-28",
    "travelClass": "1A",
    "quota": "GENERAL",
    "fareAmount": 1915,
    "status": "RAC",
    "racPosition": 22,
    "confirmationLikelihood": 0.65
  },
  {
    "trainNumber": "20046",
    "journeyDate": "2026-08-24",
    "travelClass": "SL",
    "quota": "GENERAL",
    "fareAmount": 1684,
    "status": "RLWL",
    "waitlistPosition": 3,
    "confirmationLikelihood": 0.56
  },
  {
    "trainNumber": "20046",
    "journeyDate": "2026-08-26",
    "travelClass": "SL",
    "quota": "GENERAL",
    "fareAmount": 1701,
    "status": "SOLD_OUT",
    "confirmationLikelihood": 0
  },
  {
    "trainNumber": "20046",
    "journeyDate": "2026-08-28",
    "travelClass": "SL",
    "quota": "GENERAL",
    "fareAmount": 1718,
    "status": "CNF",
    "confirmedSeatsRemaining": 9,
    "confirmationLikelihood": 1
  },
  {
    "trainNumber": "20047",
    "journeyDate": "2026-08-24",
    "travelClass": "CC",
    "quota": "GENERAL",
    "fareAmount": 1713,
    "status": "SOLD_OUT",
    "confirmationLikelihood": 0
  },
  {
    "trainNumber": "20047",
    "journeyDate": "2026-08-26",
    "travelClass": "CC",
    "quota": "GENERAL",
    "fareAmount": 1730,
    "status": "CNF",
    "confirmedSeatsRemaining": 9,
    "confirmationLikelihood": 1
  },
  {
    "trainNumber": "20047",
    "journeyDate": "2026-08-28",
    "travelClass": "CC",
    "quota": "GENERAL",
    "fareAmount": 1747,
    "status": "RAC",
    "racPosition": 24,
    "confirmationLikelihood": 0.75
  },
  {
    "trainNumber": "20048",
    "journeyDate": "2026-08-24",
    "travelClass": "SL",
    "quota": "GENERAL",
    "fareAmount": 1742,
    "status": "CNF",
    "confirmedSeatsRemaining": 9,
    "confirmationLikelihood": 1
  },
  {
    "trainNumber": "20048",
    "journeyDate": "2026-08-26",
    "travelClass": "SL",
    "quota": "GENERAL",
    "fareAmount": 1759,
    "status": "RAC",
    "racPosition": 22,
    "confirmationLikelihood": 0.6
  },
  {
    "trainNumber": "20048",
    "journeyDate": "2026-08-28",
    "travelClass": "SL",
    "quota": "GENERAL",
    "fareAmount": 1776,
    "status": "GNWL",
    "waitlistPosition": 67,
    "confirmationLikelihood": 0.1
  },
  {
    "trainNumber": "20048",
    "journeyDate": "2026-08-24",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 1855,
    "status": "RAC",
    "racPosition": 19,
    "confirmationLikelihood": 0.6
  },
  {
    "trainNumber": "20048",
    "journeyDate": "2026-08-26",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 1872,
    "status": "GNWL",
    "waitlistPosition": 66,
    "confirmationLikelihood": 0.11
  },
  {
    "trainNumber": "20048",
    "journeyDate": "2026-08-28",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 1889,
    "status": "PQWL",
    "waitlistPosition": 3,
    "confirmationLikelihood": 0.66
  },
  {
    "trainNumber": "20048",
    "journeyDate": "2026-08-24",
    "travelClass": "2A",
    "quota": "GENERAL",
    "fareAmount": 1968,
    "status": "GNWL",
    "waitlistPosition": 65,
    "confirmationLikelihood": 0.12
  },
  {
    "trainNumber": "20048",
    "journeyDate": "2026-08-26",
    "travelClass": "2A",
    "quota": "GENERAL",
    "fareAmount": 1985,
    "status": "PQWL",
    "waitlistPosition": 2,
    "confirmationLikelihood": 0.68
  },
  {
    "trainNumber": "20048",
    "journeyDate": "2026-08-28",
    "travelClass": "2A",
    "quota": "GENERAL",
    "fareAmount": 2002,
    "status": "RLWL",
    "waitlistPosition": 19,
    "confirmationLikelihood": 0.37
  },
  {
    "trainNumber": "20048",
    "journeyDate": "2026-08-24",
    "travelClass": "1A",
    "quota": "GENERAL",
    "fareAmount": 2081,
    "status": "PQWL",
    "waitlistPosition": 1,
    "confirmationLikelihood": 0.69
  },
  {
    "trainNumber": "20048",
    "journeyDate": "2026-08-26",
    "travelClass": "1A",
    "quota": "GENERAL",
    "fareAmount": 2098,
    "status": "RLWL",
    "waitlistPosition": 18,
    "confirmationLikelihood": 0.38
  },
  {
    "trainNumber": "20048",
    "journeyDate": "2026-08-28",
    "travelClass": "1A",
    "quota": "GENERAL",
    "fareAmount": 2115,
    "status": "SOLD_OUT",
    "confirmationLikelihood": 0
  },
  {
    "trainNumber": "20049",
    "journeyDate": "2026-08-24",
    "travelClass": "SL",
    "quota": "GENERAL",
    "fareAmount": 1771,
    "status": "RAC",
    "racPosition": 20,
    "confirmationLikelihood": 0.65
  },
  {
    "trainNumber": "20049",
    "journeyDate": "2026-08-26",
    "travelClass": "SL",
    "quota": "GENERAL",
    "fareAmount": 1788,
    "status": "GNWL",
    "waitlistPosition": 69,
    "confirmationLikelihood": 0.07
  },
  {
    "trainNumber": "20049",
    "journeyDate": "2026-08-28",
    "travelClass": "SL",
    "quota": "GENERAL",
    "fareAmount": 1805,
    "status": "PQWL",
    "waitlistPosition": 8,
    "confirmationLikelihood": 0.6
  },
  {
    "trainNumber": "20049",
    "journeyDate": "2026-08-24",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 1884,
    "status": "GNWL",
    "waitlistPosition": 68,
    "confirmationLikelihood": 0.08
  },
  {
    "trainNumber": "20049",
    "journeyDate": "2026-08-26",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 1901,
    "status": "PQWL",
    "waitlistPosition": 7,
    "confirmationLikelihood": 0.62
  },
  {
    "trainNumber": "20049",
    "journeyDate": "2026-08-28",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 1918,
    "status": "RLWL",
    "waitlistPosition": 26,
    "confirmationLikelihood": 0.29
  },
  {
    "trainNumber": "20050",
    "journeyDate": "2026-08-24",
    "travelClass": "SL",
    "quota": "GENERAL",
    "fareAmount": 1800,
    "status": "GNWL",
    "waitlistPosition": 71,
    "confirmationLikelihood": 0.05
  },
  {
    "trainNumber": "20050",
    "journeyDate": "2026-08-26",
    "travelClass": "SL",
    "quota": "GENERAL",
    "fareAmount": 1817,
    "status": "PQWL",
    "waitlistPosition": 12,
    "confirmationLikelihood": 0.56
  },
  {
    "trainNumber": "20050",
    "journeyDate": "2026-08-28",
    "travelClass": "SL",
    "quota": "GENERAL",
    "fareAmount": 1834,
    "status": "RLWL",
    "waitlistPosition": 33,
    "confirmationLikelihood": 0.2
  },
  {
    "trainNumber": "20050",
    "journeyDate": "2026-08-24",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 1913,
    "status": "PQWL",
    "waitlistPosition": 11,
    "confirmationLikelihood": 0.57
  },
  {
    "trainNumber": "20050",
    "journeyDate": "2026-08-26",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 1930,
    "status": "RLWL",
    "waitlistPosition": 32,
    "confirmationLikelihood": 0.22
  },
  {
    "trainNumber": "20050",
    "journeyDate": "2026-08-28",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 1947,
    "status": "SOLD_OUT",
    "confirmationLikelihood": 0
  },
  {
    "trainNumber": "20050",
    "journeyDate": "2026-08-24",
    "travelClass": "2A",
    "quota": "GENERAL",
    "fareAmount": 2026,
    "status": "RLWL",
    "waitlistPosition": 31,
    "confirmationLikelihood": 0.23
  },
  {
    "trainNumber": "20050",
    "journeyDate": "2026-08-26",
    "travelClass": "2A",
    "quota": "GENERAL",
    "fareAmount": 2043,
    "status": "SOLD_OUT",
    "confirmationLikelihood": 0
  },
  {
    "trainNumber": "20050",
    "journeyDate": "2026-08-28",
    "travelClass": "2A",
    "quota": "GENERAL",
    "fareAmount": 2060,
    "status": "CNF",
    "confirmedSeatsRemaining": 13,
    "confirmationLikelihood": 1
  },
  {
    "trainNumber": "20051",
    "journeyDate": "2026-08-24",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 1829,
    "status": "PQWL",
    "waitlistPosition": 16,
    "confirmationLikelihood": 0.51
  },
  {
    "trainNumber": "20051",
    "journeyDate": "2026-08-26",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 1846,
    "status": "RLWL",
    "waitlistPosition": 39,
    "confirmationLikelihood": 0.13
  },
  {
    "trainNumber": "20051",
    "journeyDate": "2026-08-28",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 1863,
    "status": "SOLD_OUT",
    "confirmationLikelihood": 0
  },
  {
    "trainNumber": "20051",
    "journeyDate": "2026-08-24",
    "travelClass": "2A",
    "quota": "GENERAL",
    "fareAmount": 1942,
    "status": "RLWL",
    "waitlistPosition": 38,
    "confirmationLikelihood": 0.14
  },
  {
    "trainNumber": "20051",
    "journeyDate": "2026-08-26",
    "travelClass": "2A",
    "quota": "GENERAL",
    "fareAmount": 1959,
    "status": "SOLD_OUT",
    "confirmationLikelihood": 0
  },
  {
    "trainNumber": "20051",
    "journeyDate": "2026-08-28",
    "travelClass": "2A",
    "quota": "GENERAL",
    "fareAmount": 1976,
    "status": "CNF",
    "confirmedSeatsRemaining": 14,
    "confirmationLikelihood": 1
  },
  {
    "trainNumber": "20052",
    "journeyDate": "2026-08-24",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 1858,
    "status": "RLWL",
    "waitlistPosition": 45,
    "confirmationLikelihood": 0.06
  },
  {
    "trainNumber": "20052",
    "journeyDate": "2026-08-26",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 1875,
    "status": "SOLD_OUT",
    "confirmationLikelihood": 0
  },
  {
    "trainNumber": "20052",
    "journeyDate": "2026-08-28",
    "travelClass": "3A",
    "quota": "GENERAL",
    "fareAmount": 1892,
    "status": "CNF",
    "confirmedSeatsRemaining": 15,
    "confirmationLikelihood": 1
  },
  {
    "trainNumber": "20052",
    "journeyDate": "2026-08-24",
    "travelClass": "2A",
    "quota": "GENERAL",
    "fareAmount": 1971,
    "status": "SOLD_OUT",
    "confirmationLikelihood": 0
  },
  {
    "trainNumber": "20052",
    "journeyDate": "2026-08-26",
    "travelClass": "2A",
    "quota": "GENERAL",
    "fareAmount": 1988,
    "status": "CNF",
    "confirmedSeatsRemaining": 14,
    "confirmationLikelihood": 1
  },
  {
    "trainNumber": "20052",
    "journeyDate": "2026-08-28",
    "travelClass": "2A",
    "quota": "GENERAL",
    "fareAmount": 2005,
    "status": "RAC",
    "racPosition": 29,
    "confirmationLikelihood": 0.6
  },
  {
    "trainNumber": "20052",
    "journeyDate": "2026-08-24",
    "travelClass": "1A",
    "quota": "GENERAL",
    "fareAmount": 2084,
    "status": "CNF",
    "confirmedSeatsRemaining": 13,
    "confirmationLikelihood": 1
  },
  {
    "trainNumber": "20052",
    "journeyDate": "2026-08-26",
    "travelClass": "1A",
    "quota": "GENERAL",
    "fareAmount": 2101,
    "status": "RAC",
    "racPosition": 26,
    "confirmationLikelihood": 0.6
  },
  {
    "trainNumber": "20052",
    "journeyDate": "2026-08-28",
    "travelClass": "1A",
    "quota": "GENERAL",
    "fareAmount": 2118,
    "status": "GNWL",
    "waitlistPosition": 79,
    "confirmationLikelihood": 0.05
  },
  {
    "trainNumber": "20053",
    "journeyDate": "2026-08-24",
    "travelClass": "SL",
    "quota": "GENERAL",
    "fareAmount": 1887,
    "status": "SOLD_OUT",
    "confirmationLikelihood": 0
  },
  {
    "trainNumber": "20053",
    "journeyDate": "2026-08-26",
    "travelClass": "SL",
    "quota": "GENERAL",
    "fareAmount": 1904,
    "status": "CNF",
    "confirmedSeatsRemaining": 15,
    "confirmationLikelihood": 1
  },
  {
    "trainNumber": "20053",
    "journeyDate": "2026-08-28",
    "travelClass": "SL",
    "quota": "GENERAL",
    "fareAmount": 1921,
    "status": "RAC",
    "racPosition": 30,
    "confirmationLikelihood": 0.65
  },
  {
    "trainNumber": "20054",
    "journeyDate": "2026-08-24",
    "travelClass": "CC",
    "quota": "GENERAL",
    "fareAmount": 1916,
    "status": "CNF",
    "confirmedSeatsRemaining": 15,
    "confirmationLikelihood": 1
  },
  {
    "trainNumber": "20054",
    "journeyDate": "2026-08-26",
    "travelClass": "CC",
    "quota": "GENERAL",
    "fareAmount": 1933,
    "status": "RAC",
    "racPosition": 28,
    "confirmationLikelihood": 0.7
  },
  {
    "trainNumber": "20054",
    "journeyDate": "2026-08-28",
    "travelClass": "CC",
    "quota": "GENERAL",
    "fareAmount": 1950,
    "status": "GNWL",
    "waitlistPosition": 5,
    "confirmationLikelihood": 0.84
  }
];
