/**
 * AUTO-GENERATED by scripts/generateMockData.ts — do not hand-edit.
 * Regenerate with: npm run generate:data
 *
 * Conforms to the data contract in spec/04-data-spec.md.
 */

import type { Booking } from '../types/domain';

export const bookings: Booking[] = [
  {
    "id": "booking_seed_1",
    "pnr": "1000000001",
    "source": "SMART_SEARCH",
    "userId": "user_1",
    "trainNumber": "12703",
    "journeyDate": "2026-08-27",
    "sourceStationCode": "MAS",
    "destinationStationCode": "SC",
    "travelClass": "3A",
    "quota": "GENERAL",
    "status": "CNF",
    "fareAmount": 1100,
    "passengers": [
      {
        "passengerId": "passenger_1",
        "name": "Aravind Kumar",
        "age": 29,
        "gender": "MALE",
        "seatNumber": "34",
        "coach": "B2"
      }
    ],
    "bookedAt": "2026-08-22T09:15:00+05:30"
  },
  {
    "id": "booking_seed_2",
    "pnr": "1000000002",
    "source": "AGENT",
    "userId": "user_1",
    "trainNumber": "12728",
    "journeyDate": "2026-08-23",
    "sourceStationCode": "MAS",
    "destinationStationCode": "SC",
    "travelClass": "3A",
    "quota": "GENERAL",
    "status": "CNF",
    "fareAmount": 1350,
    "passengers": [
      {
        "passengerId": "passenger_1",
        "name": "Aravind Kumar",
        "age": 29,
        "gender": "MALE",
        "seatNumber": "12",
        "coach": "B1"
      },
      {
        "passengerId": "passenger_2",
        "name": "Priya Ramesh",
        "age": 27,
        "gender": "FEMALE",
        "seatNumber": "13",
        "coach": "B1"
      }
    ],
    "bookedAt": "2026-08-22T09:20:00+05:30"
  },
  {
    "id": "booking_seed_3",
    "pnr": "1000000003",
    "source": "TATKAL",
    "userId": "user_3",
    "trainNumber": "17015",
    "journeyDate": "2026-08-23",
    "sourceStationCode": "MAS",
    "destinationStationCode": "SC",
    "travelClass": "3A",
    "quota": "TATKAL",
    "status": "CNF",
    "fareAmount": 820,
    "passengers": [
      {
        "passengerId": "passenger_5",
        "name": "Karthik Subramanian",
        "age": 33,
        "gender": "MALE",
        "seatNumber": "5",
        "coach": "S4"
      }
    ],
    "bookedAt": "2026-08-22T10:00:15+05:30"
  }
];
