/**
 * Demo date configuration.
 *
 * DATE STRATEGY (see spec/04-data-spec.md "Open questions" and the
 * data-generation task): the product needs relative-feeling dates
 * ("tomorrow evening") while the underlying mock data must stay
 * fully deterministic — the same demo must look identical on every
 * run, regardless of the real calendar date.
 *
 * The resolution: the app's notion of "today" is a fixed constant,
 * DEMO_TODAY, not `new Date()` / `Date.now()`. All journey dates in
 * the generated mock data are expressed relative to this constant.
 * Anything that later needs "tomorrow" (e.g. the Agent capability's
 * natural-language date resolution) should resolve against
 * DEMO_TODAY, not the real current date.
 *
 * This is a prototype simplification, explicitly flagged in
 * spec/04-data-spec.md as deferred to spec/05-technical-spec.md:
 * a real implementation might make this configurable (env var,
 * settings toggle) so the demo can be "moved" without regenerating
 * data. For now it is a hard-coded constant, which is sufficient for
 * a deterministic hackathon demo.
 *
 * This file is hand-written and is NOT regenerated by
 * scripts/generateMockData.ts — the generator imports DEMO_TODAY and
 * addDays from here so both the generator and any future app code
 * share a single source of truth for "what day is it, for demo
 * purposes."
 */

import type { ISODate } from '../types/domain';

/** The fixed reference "today" for all generated demo data. */
export const DEMO_TODAY: ISODate = '2026-08-22';

/** Add `days` calendar days to an ISO date, returning an ISO date. */
export function addDays(date: ISODate, days: number): ISODate {
  const [year, month, day] = date.split('-').map(Number);
  const d = new Date(Date.UTC(year, month - 1, day));
  d.setUTCDate(d.getUTCDate() + days);
  const y = d.getUTCFullYear();
  const m = String(d.getUTCMonth() + 1).padStart(2, '0');
  const dd = String(d.getUTCDate()).padStart(2, '0');
  return `${y}-${m}-${dd}`;
}

/** Named demo dates used throughout the generated dataset. */
export const DEMO_DATES = {
  /** "Today" — used as the Tatkal countdown/opening reference point. */
  TODAY: DEMO_TODAY,
  /** "Tomorrow" — Agent scenario ("tomorrow evening") and Tatkal journey date. */
  TOMORROW: addDays(DEMO_TODAY, 1),
  /** Primary Smart Search demo date (Best Overall / Fastest trio, Partial state). */
  SEARCH_DEMO: addDays(DEMO_TODAY, 2),
  /**
   * Status Translator demo date (GNWL/RAC lookups) and the sold-out
   * edge-case train. Deliberately separate from SEARCH_DEMO: these
   * scenarios only assert that a specific train/status exists, not
   * the shape of the whole candidate pool, but they were originally
   * placed on the same MAS→SC/SEARCH_DEMO slot as the Best Overall
   * trio, which meant a real Smart Search on that date returned a
   * larger, unintended pool. Moved here so SEARCH_DEMO contains only
   * the trio it's meant to demonstrate.
   */
  STATUS_DEMO: addDays(DEMO_TODAY, 3),
  /** A secondary date used only for filler/volume data, for variety. */
  SECONDARY: addDays(DEMO_TODAY, 4),
  /**
   * Cheapest-trade-off demo date (₹700 GNWL vs ₹1,100 CNF). Needs its
   * own isolated date — unlike the Status Translator trains above,
   * this scenario's assertion is sensitive to exactly which other
   * options are in the pool, so it can't safely share a date with
   * anything else on the MAS→SC route.
   */
  CHEAPEST_DEMO: addDays(DEMO_TODAY, 5),
} as const;
