/**
 * AUTO-GENERATED by scripts/generateMockData.ts — do not hand-edit.
 * Regenerate with: npm run generate:data
 *
 * Conforms to the data contract in spec/04-data-spec.md.
 */

import type { Passenger } from '../types/domain';

export const passengers: Passenger[] = [
  {
    "id": "passenger_1",
    "name": "Aravind Kumar",
    "age": 29,
    "gender": "MALE",
    "isSaved": true
  },
  {
    "id": "passenger_2",
    "name": "Priya Ramesh",
    "age": 27,
    "gender": "FEMALE",
    "isSaved": true
  },
  {
    "id": "passenger_3",
    "name": "Suresh Iyer",
    "age": 54,
    "gender": "MALE",
    "isSaved": true
  },
  {
    "id": "passenger_4",
    "name": "Lakshmi Narayanan",
    "age": 51,
    "gender": "FEMALE",
    "isSaved": true
  },
  {
    "id": "passenger_5",
    "name": "Karthik Subramanian",
    "age": 33,
    "gender": "MALE",
    "isSaved": true
  },
  {
    "id": "passenger_6",
    "name": "Divya Menon",
    "age": 24,
    "gender": "FEMALE",
    "isSaved": false
  },
  {
    "id": "passenger_7",
    "name": "Rahul Verma",
    "age": 41,
    "gender": "MALE",
    "isSaved": false
  }
];
