/**
 * AUTO-GENERATED by scripts/generateMockData.ts — do not hand-edit.
 * Regenerate with: npm run generate:data
 *
 * Conforms to the data contract in spec/04-data-spec.md.
 */

import type { DemoScenario } from '../types/domain';

export const demoScenarios: DemoScenario[] = [
  {
    "id": "demo_status_translator_gnwl24",
    "purpose": "Status Translator: explain GNWL 24 in plain language with an actionable alternative.",
    "searchInput": {
      "sourceStationCode": "MAS",
      "destinationStationCode": "SC",
      "journeyDate": "2026-08-25",
      "passengerCount": 1,
      "preferredClass": "3A"
    },
    "expectedTrainNumbers": [
      "12759"
    ],
    "expectedStatuses": [
      {
        "trainNumber": "12759",
        "travelClass": "3A",
        "status": "GNWL"
      }
    ],
    "expectedOutcome": "Understand My Status / inline explanation shows: \"You're #24 on the General Wait List. Your ticket is not confirmed yet,\" with a suggestion to consider a backup."
  },
  {
    "id": "demo_status_translator_rac14",
    "purpose": "Status Translator: explain RAC 14 in plain language.",
    "searchInput": {
      "sourceStationCode": "MAS",
      "destinationStationCode": "SC",
      "journeyDate": "2026-08-25",
      "passengerCount": 1,
      "preferredClass": "3A"
    },
    "expectedTrainNumbers": [
      "17406"
    ],
    "expectedStatuses": [
      {
        "trainNumber": "17406",
        "travelClass": "3A",
        "status": "RAC"
      }
    ],
    "expectedOutcome": "Inline explanation shows: \"You're #14 on RAC. You can board and travel, sharing a berth with one other RAC passenger.\""
  },
  {
    "id": "demo_best_overall",
    "purpose": "Smart Search: three meaningfully different options produce a clear Best Overall pick.",
    "searchInput": {
      "sourceStationCode": "MAS",
      "destinationStationCode": "SC",
      "journeyDate": "2026-08-24",
      "passengerCount": 1,
      "preferredClass": "3A",
      "travelPriority": "BALANCED"
    },
    "expectedTrainNumbers": [
      "12760",
      "17654",
      "12604"
    ],
    "expectedRecommendations": [
      {
        "category": "BEST_OVERALL",
        "trainNumber": "12604"
      },
      {
        "category": "CHEAPEST",
        "trainNumber": "17654"
      },
      {
        "category": "FASTEST",
        "trainNumber": "12604"
      }
    ],
    "expectedStatuses": [
      {
        "trainNumber": "12760",
        "travelClass": "3A",
        "status": "CNF"
      },
      {
        "trainNumber": "17654",
        "travelClass": "3A",
        "status": "GNWL"
      },
      {
        "trainNumber": "12604",
        "travelClass": "3A",
        "status": "CNF"
      }
    ],
    "expectedOutcome": "Results shows Best Overall and Fastest both pointing to the confirmed, quickest train (₹1,680, Confirmed, 9h40m) — the UI states plainly that these two categories agree — alongside a Confirmed ₹1,240/12h50m alternative and (intended) a Cheapest pick at ₹780/GNWL 42/13h20m."
  },
  {
    "id": "demo_cheapest_tradeoff",
    "purpose": "Smart Search: cheapest option carries a visible, honest waitlist trade-off.",
    "searchInput": {
      "sourceStationCode": "MAS",
      "destinationStationCode": "SC",
      "journeyDate": "2026-08-27",
      "passengerCount": 1,
      "travelPriority": "PRICE"
    },
    "expectedTrainNumbers": [
      "17015",
      "12703"
    ],
    "expectedRecommendations": [
      {
        "category": "CHEAPEST",
        "trainNumber": "17015"
      }
    ],
    "expectedStatuses": [
      {
        "trainNumber": "17015",
        "travelClass": "SL",
        "status": "GNWL"
      },
      {
        "trainNumber": "12703",
        "travelClass": "3A",
        "status": "CNF"
      }
    ],
    "expectedOutcome": "UI communicates \"Save ₹400, but accept waitlist risk\" comparing ₹700 GNWL 8 to ₹1,100 Confirmed."
  },
  {
    "id": "demo_fastest_not_cheapest",
    "purpose": "Smart Search: fastest option is not the cheapest, showing different users value different things.",
    "searchInput": {
      "sourceStationCode": "MAS",
      "destinationStationCode": "SC",
      "journeyDate": "2026-08-24",
      "passengerCount": 1,
      "travelPriority": "SPEED"
    },
    "expectedTrainNumbers": [
      "12760",
      "12604"
    ],
    "expectedRecommendations": [
      {
        "category": "FASTEST",
        "trainNumber": "12604"
      }
    ],
    "expectedStatuses": [
      {
        "trainNumber": "12760",
        "travelClass": "3A",
        "status": "CNF"
      },
      {
        "trainNumber": "12604",
        "travelClass": "3A",
        "status": "CNF"
      }
    ],
    "expectedOutcome": "Fastest (₹1,680, 9h40m) is clearly pricier than the ₹1,240 / 12h50m Best Overall option."
  },
  {
    "id": "demo_best_confirmation_chance_partial",
    "purpose": "Smart Search: no confirmed option exists at all on this route/date — Results must show the \"Partial\" state honestly and still surface a Best Chance of Confirmation.",
    "searchInput": {
      "sourceStationCode": "SBC",
      "destinationStationCode": "HWH",
      "journeyDate": "2026-08-24",
      "passengerCount": 1,
      "travelPriority": "CONFIRMATION"
    },
    "expectedTrainNumbers": [
      "12864",
      "12246",
      "18646"
    ],
    "expectedRecommendations": [
      {
        "category": "BEST_CONFIRMATION_CHANCE",
        "trainNumber": "12864"
      }
    ],
    "expectedStatuses": [
      {
        "trainNumber": "12864",
        "travelClass": "3A",
        "status": "GNWL"
      },
      {
        "trainNumber": "12246",
        "travelClass": "3A",
        "status": "PQWL"
      },
      {
        "trainNumber": "18646",
        "travelClass": "3A",
        "status": "RLWL"
      }
    ],
    "expectedOutcome": "Results honestly shows only waitlisted options; GNWL 5 (highest confirmation likelihood) is labeled Best Chance of Confirmation rather than hiding the category."
  },
  {
    "id": "demo_agent_hyderabad",
    "purpose": "Agent-Driven Booking: extract intent from a natural-language request and recommend with trade-offs.",
    "agentInputText": "I need to reach Hyderabad tomorrow evening. Two people. AC. Preferably confirmed.",
    "expectedAgentIntent": {
      "destinationStationCode": "SC",
      "dateExpression": "tomorrow",
      "resolvedDate": "2026-08-23",
      "timePreference": "EVENING",
      "passengerCount": 2,
      "preferredClass": "3A",
      "confirmationPreference": "PREFER_CONFIRMED",
      "missingRequiredFields": []
    },
    "expectedTrainNumbers": [
      "12728",
      "12766",
      "17603"
    ],
    "expectedRecommendations": [
      {
        "category": "BEST_OVERALL",
        "trainNumber": "12728"
      }
    ],
    "expectedOutcome": "Agent recommends the ₹1,350 Confirmed 3A option, with the ₹980 GNWL 12 option and the ₹2,100 Confirmed 2A option available as alternatives with stated trade-offs."
  },
  {
    "id": "demo_tatkal_success",
    "purpose": "Tatkal Mode: preferred train is available and the booking attempt succeeds directly.",
    "tatkalScenario": {
      "preparationId": "tatkal_prep_success",
      "expectedPreferredOutcome": "CNF",
      "expectedBackupOutcomes": []
    },
    "expectedOutcome": "Booking Attempt succeeds immediately on the preferred train; backup is never needed."
  },
  {
    "id": "demo_tatkal_failure_backup",
    "purpose": "HERO: Tatkal Mode preferred train is sold out, first backup confirms — demonstrates fallback without restarting the flow.",
    "tatkalScenario": {
      "preparationId": "tatkal_prep_failure_backup",
      "expectedPreferredOutcome": "REGRET",
      "expectedBackupOutcomes": [
        "CNF",
        "CNF"
      ]
    },
    "expectedOutcome": "Preferred train shows SOLD_OUT and fails; backup options appear immediately in place; user selects the first backup and it confirms."
  },
  {
    "id": "demo_tatkal_tqwl_fallback",
    "purpose": "Tatkal Mode: preferred train lands on the Tatkal Waitlist (not sold out, not confirmed) and falls back to a backup.",
    "tatkalScenario": {
      "preparationId": "tatkal_prep_tqwl_demo",
      "expectedPreferredOutcome": "REGRET",
      "expectedBackupOutcomes": [
        "CNF"
      ]
    },
    "expectedOutcome": "Preferred train shows TQWL 6 (Tatkal-quota waitlist) at attempt time, treated as not-yet-confirmed; the single backup confirms."
  }
];
