/**
 * AUTO-GENERATED by scripts/generateMockData.ts — do not hand-edit.
 * Regenerate with: npm run generate:data
 *
 * Conforms to the data contract in spec/04-data-spec.md.
 */

import type { RailwayStatusDefinition } from '../types/domain';

export const statusDefinitions: RailwayStatusDefinition[] = [
  {
    "code": "CNF",
    "displayLabel": "Confirmed",
    "category": "CONFIRMED",
    "canBoard": true,
    "isFullyConfirmed": true,
    "isWaitlisted": false,
    "positionApplicable": false,
    "plainExplanation": "Your seat or berth is confirmed. You have a guaranteed place on this train.",
    "isLiveAvailabilityStatus": true
  },
  {
    "code": "RAC",
    "displayLabel": "RAC (Reservation Against Cancellation)",
    "category": "PARTIALLY_CONFIRMED",
    "canBoard": true,
    "isFullyConfirmed": false,
    "isWaitlisted": false,
    "positionApplicable": true,
    "plainExplanation": "You're #{position} on RAC. You can board and travel, sharing a berth with one other RAC passenger.",
    "suggestedConsideration": "You can travel as-is. If other passengers cancel, you may later be upgraded to your own confirmed berth.",
    "isLiveAvailabilityStatus": true
  },
  {
    "code": "GNWL",
    "displayLabel": "General Waitlist",
    "category": "WAITLISTED",
    "canBoard": false,
    "isFullyConfirmed": false,
    "isWaitlisted": true,
    "positionApplicable": true,
    "plainExplanation": "You're currently #{position} on the General Wait List. Your ticket is not confirmed yet.",
    "suggestedConsideration": "Consider a backup train or a different class with better availability, especially if your travel date is fixed.",
    "isLiveAvailabilityStatus": true
  },
  {
    "code": "PQWL",
    "displayLabel": "Pooled Quota Waitlist",
    "category": "WAITLISTED",
    "canBoard": false,
    "isFullyConfirmed": false,
    "isWaitlisted": true,
    "positionApplicable": true,
    "plainExplanation": "You're #{position} on a Pooled Quota Wait List — a shared waitlist for a shorter part of this train's overall journey.",
    "suggestedConsideration": "Pooled quota tends to move slower than the general waitlist. A different train or class may confirm sooner.",
    "isLiveAvailabilityStatus": true
  },
  {
    "code": "RLWL",
    "displayLabel": "Remote Location Waitlist",
    "category": "WAITLISTED",
    "canBoard": false,
    "isFullyConfirmed": false,
    "isWaitlisted": true,
    "positionApplicable": true,
    "plainExplanation": "You're #{position} on a Remote Location Wait List, tied to a specific stop along this train's route rather than its starting station.",
    "suggestedConsideration": "This waitlist is often slower to confirm than a General Waitlist. Check other trains if your plans are firm.",
    "isLiveAvailabilityStatus": true
  },
  {
    "code": "TQWL",
    "displayLabel": "Tatkal Waitlist",
    "category": "WAITLISTED",
    "canBoard": false,
    "isFullyConfirmed": false,
    "isWaitlisted": true,
    "positionApplicable": true,
    "plainExplanation": "You're #{position} on the Tatkal Wait List. Tatkal quota is small, so this is less likely to confirm than a regular waitlist.",
    "suggestedConsideration": "Have a backup train ready — Tatkal waitlists confirm less often than general ones.",
    "isLiveAvailabilityStatus": true
  },
  {
    "code": "WL",
    "displayLabel": "Waitlisted (general term)",
    "category": "WAITLISTED",
    "canBoard": false,
    "isFullyConfirmed": false,
    "isWaitlisted": true,
    "positionApplicable": true,
    "plainExplanation": "\"WL\" is a general term for any waitlisted status. The specific type (GNWL, PQWL, RLWL, or TQWL) determines how likely it is to confirm.",
    "suggestedConsideration": "Look up the specific waitlist type shown on your ticket for a clearer picture.",
    "isLiveAvailabilityStatus": false
  },
  {
    "code": "SOLD_OUT",
    "displayLabel": "Sold Out",
    "category": "UNAVAILABLE",
    "canBoard": false,
    "isFullyConfirmed": false,
    "isWaitlisted": false,
    "positionApplicable": false,
    "plainExplanation": "No seats and no further waitlist spots are available for this train, date, and class.",
    "suggestedConsideration": "Try a different train, class, or nearby date.",
    "isLiveAvailabilityStatus": true
  },
  {
    "code": "CAN",
    "displayLabel": "Cancelled",
    "category": "CANCELLED",
    "canBoard": false,
    "isFullyConfirmed": false,
    "isWaitlisted": false,
    "positionApplicable": false,
    "plainExplanation": "This booking was cancelled and is no longer valid for travel.",
    "suggestedConsideration": "If you still need to travel, search for a new option.",
    "isLiveAvailabilityStatus": false
  },
  {
    "code": "REGRET",
    "displayLabel": "Booking Not Possible",
    "category": "FAILED",
    "canBoard": false,
    "isFullyConfirmed": false,
    "isWaitlisted": false,
    "positionApplicable": false,
    "plainExplanation": "This booking attempt could not be completed — no seats, waitlist spots, or RAC were available.",
    "suggestedConsideration": "Check the backup options already prepared, or start a new search.",
    "isLiveAvailabilityStatus": false
  }
];
