/**
 * AUTO-GENERATED by scripts/generateMockData.ts — do not hand-edit.
 * Regenerate with: npm run generate:data
 *
 * Conforms to the data contract in spec/04-data-spec.md.
 */

import type { Station } from '../types/domain';

export const stations: Station[] = [
  {
    "code": "MAS",
    "name": "Chennai Central",
    "city": "Chennai",
    "state": "Tamil Nadu"
  },
  {
    "code": "SC",
    "name": "Secunderabad Jn",
    "city": "Hyderabad",
    "state": "Telangana"
  },
  {
    "code": "HYB",
    "name": "Hyderabad Deccan",
    "city": "Hyderabad",
    "state": "Telangana"
  },
  {
    "code": "SBC",
    "name": "Bengaluru City Jn",
    "city": "Bengaluru",
    "state": "Karnataka"
  },
  {
    "code": "CSMT",
    "name": "Mumbai CST",
    "city": "Mumbai",
    "state": "Maharashtra"
  },
  {
    "code": "BCT",
    "name": "Mumbai Central",
    "city": "Mumbai",
    "state": "Maharashtra"
  },
  {
    "code": "NDLS",
    "name": "New Delhi",
    "city": "Delhi",
    "state": "Delhi"
  },
  {
    "code": "HWH",
    "name": "Howrah Jn",
    "city": "Kolkata",
    "state": "West Bengal"
  },
  {
    "code": "PUNE",
    "name": "Pune Jn",
    "city": "Pune",
    "state": "Maharashtra"
  },
  {
    "code": "ADI",
    "name": "Ahmedabad Jn",
    "city": "Ahmedabad",
    "state": "Gujarat"
  },
  {
    "code": "CBE",
    "name": "Coimbatore Jn",
    "city": "Coimbatore",
    "state": "Tamil Nadu"
  },
  {
    "code": "MDU",
    "name": "Madurai Jn",
    "city": "Madurai",
    "state": "Tamil Nadu"
  },
  {
    "code": "ERS",
    "name": "Ernakulam Jn",
    "city": "Kochi",
    "state": "Kerala"
  },
  {
    "code": "BZA",
    "name": "Vijayawada Jn",
    "city": "Vijayawada",
    "state": "Andhra Pradesh"
  },
  {
    "code": "VSKP",
    "name": "Visakhapatnam",
    "city": "Visakhapatnam",
    "state": "Andhra Pradesh"
  },
  {
    "code": "JP",
    "name": "Jaipur Jn",
    "city": "Jaipur",
    "state": "Rajasthan"
  },
  {
    "code": "BPL",
    "name": "Bhopal Jn",
    "city": "Bhopal",
    "state": "Madhya Pradesh"
  },
  {
    "code": "LKO",
    "name": "Lucknow Charbagh",
    "city": "Lucknow",
    "state": "Uttar Pradesh"
  },
  {
    "code": "BSB",
    "name": "Varanasi Jn",
    "city": "Varanasi",
    "state": "Uttar Pradesh"
  },
  {
    "code": "PNBE",
    "name": "Patna Jn",
    "city": "Patna",
    "state": "Bihar"
  },
  {
    "code": "BBS",
    "name": "Bhubaneswar",
    "city": "Bhubaneswar",
    "state": "Odisha"
  },
  {
    "code": "MYS",
    "name": "Mysuru Jn",
    "city": "Mysuru",
    "state": "Karnataka"
  },
  {
    "code": "NGP",
    "name": "Nagpur Jn",
    "city": "Nagpur",
    "state": "Maharashtra"
  },
  {
    "code": "ST",
    "name": "Surat",
    "city": "Surat",
    "state": "Gujarat"
  },
  {
    "code": "INDB",
    "name": "Indore Jn",
    "city": "Indore",
    "state": "Madhya Pradesh"
  },
  {
    "code": "GHY",
    "name": "Guwahati",
    "city": "Guwahati",
    "state": "Assam"
  },
  {
    "code": "CDG",
    "name": "Chandigarh",
    "city": "Chandigarh",
    "state": "Chandigarh"
  },
  {
    "code": "ASR",
    "name": "Amritsar Jn",
    "city": "Amritsar",
    "state": "Punjab"
  },
  {
    "code": "TVC",
    "name": "Thiruvananthapuram Central",
    "city": "Thiruvananthapuram",
    "state": "Kerala"
  },
  {
    "code": "SA",
    "name": "Salem Jn",
    "city": "Salem",
    "state": "Tamil Nadu"
  },
  {
    "code": "TPJ",
    "name": "Tiruchirapalli Jn",
    "city": "Tiruchirapalli",
    "state": "Tamil Nadu"
  },
  {
    "code": "KZJ",
    "name": "Kazipet Jn",
    "city": "Warangal",
    "state": "Telangana"
  },
  {
    "code": "NK",
    "name": "Nashik Road",
    "city": "Nashik",
    "state": "Maharashtra"
  },
  {
    "code": "JBP",
    "name": "Jabalpur",
    "city": "Jabalpur",
    "state": "Madhya Pradesh"
  },
  {
    "code": "R",
    "name": "Raipur Jn",
    "city": "Raipur",
    "state": "Chhattisgarh"
  },
  {
    "code": "RNC",
    "name": "Ranchi",
    "city": "Ranchi",
    "state": "Jharkhand"
  },
  {
    "code": "DDN",
    "name": "Dehradun",
    "city": "Dehradun",
    "state": "Uttarakhand"
  },
  {
    "code": "AGC",
    "name": "Agra Cantt",
    "city": "Agra",
    "state": "Uttar Pradesh"
  },
  {
    "code": "CNB",
    "name": "Kanpur Central",
    "city": "Kanpur",
    "state": "Uttar Pradesh"
  },
  {
    "code": "PRYJ",
    "name": "Prayagraj Jn",
    "city": "Prayagraj",
    "state": "Uttar Pradesh"
  },
  {
    "code": "GWL",
    "name": "Gwalior",
    "city": "Gwalior",
    "state": "Madhya Pradesh"
  },
  {
    "code": "JU",
    "name": "Jodhpur Jn",
    "city": "Jodhpur",
    "state": "Rajasthan"
  },
  {
    "code": "UDZ",
    "name": "Udaipur City",
    "city": "Udaipur",
    "state": "Rajasthan"
  },
  {
    "code": "RJT",
    "name": "Rajkot Jn",
    "city": "Rajkot",
    "state": "Gujarat"
  },
  {
    "code": "BRC",
    "name": "Vadodara Jn",
    "city": "Vadodara",
    "state": "Gujarat"
  },
  {
    "code": "NLR",
    "name": "Nellore",
    "city": "Nellore",
    "state": "Andhra Pradesh"
  },
  {
    "code": "RJY",
    "name": "Rajahmundry",
    "city": "Rajahmundry",
    "state": "Andhra Pradesh"
  },
  {
    "code": "TPTY",
    "name": "Tirupati",
    "city": "Tirupati",
    "state": "Andhra Pradesh"
  },
  {
    "code": "UBL",
    "name": "Hubballi Jn",
    "city": "Hubballi",
    "state": "Karnataka"
  },
  {
    "code": "MAQ",
    "name": "Mangaluru Central",
    "city": "Mangaluru",
    "state": "Karnataka"
  },
  {
    "code": "GNT",
    "name": "Guntur Jn",
    "city": "Guntur",
    "state": "Andhra Pradesh"
  }
];
