/**
 * AUTO-GENERATED by scripts/generateMockData.ts — do not hand-edit.
 * Regenerate with: npm run generate:data
 *
 * Conforms to the data contract in spec/04-data-spec.md.
 */

import type { TatkalPreparation, TatkalAttempt } from '../types/domain';

export const tatkalPreparations: TatkalPreparation[] = [
  {
    "id": "tatkal_prep_success",
    "userId": "user_1",
    "sourceStationCode": "MAS",
    "destinationStationCode": "SC",
    "journeyDate": "2026-08-23",
    "passengerIds": [
      "passenger_1",
      "passenger_2"
    ],
    "preferredClass": "3A",
    "preferredTrainNumber": "17406",
    "backupTrainNumbers": [
      "17015"
    ],
    "isReady": true,
    "tatkalOpensAt": "2026-08-22T10:00:00+05:30"
  },
  {
    "id": "tatkal_prep_failure_backup",
    "userId": "user_1",
    "sourceStationCode": "MAS",
    "destinationStationCode": "SC",
    "journeyDate": "2026-08-23",
    "passengerIds": [
      "passenger_1",
      "passenger_2"
    ],
    "preferredClass": "3A",
    "preferredTrainNumber": "12760",
    "backupTrainNumbers": [
      "17654",
      "12604"
    ],
    "isReady": true,
    "tatkalOpensAt": "2026-08-22T10:00:00+05:30"
  },
  {
    "id": "tatkal_prep_tqwl_demo",
    "userId": "user_3",
    "sourceStationCode": "MAS",
    "destinationStationCode": "SC",
    "journeyDate": "2026-08-23",
    "passengerIds": [
      "passenger_5"
    ],
    "preferredClass": "3A",
    "preferredTrainNumber": "12759",
    "backupTrainNumbers": [
      "17015"
    ],
    "isReady": true,
    "tatkalOpensAt": "2026-08-22T10:00:00+05:30"
  }
];

export const tatkalAttempts: TatkalAttempt[] = [];
