/**
 * AUTO-GENERATED by scripts/generateMockData.ts — do not hand-edit.
 * Regenerate with: npm run generate:data
 *
 * Conforms to the data contract in spec/04-data-spec.md.
 */

import type { Train } from '../types/domain';

export const trains: Train[] = [
  {
    "number": "12760",
    "name": "Charminar SF Express",
    "trainType": "SUPERFAST",
    "sourceStationCode": "MAS",
    "destinationStationCode": "SC",
    "routeStationCodes": [
      "MAS",
      "BZA",
      "SC"
    ],
    "departureTime": "18:00",
    "arrivalTime": "06:50",
    "arrivalDayOffset": 1,
    "durationMinutes": 770,
    "supportedClasses": [
      "SL",
      "3A",
      "2A"
    ],
    "operatingDays": "DAILY"
  },
  {
    "number": "17654",
    "name": "Deccan Express",
    "trainType": "EXPRESS",
    "sourceStationCode": "MAS",
    "destinationStationCode": "SC",
    "routeStationCodes": [
      "MAS",
      "BZA",
      "SC"
    ],
    "departureTime": "19:10",
    "arrivalTime": "08:30",
    "arrivalDayOffset": 1,
    "durationMinutes": 800,
    "supportedClasses": [
      "SL",
      "3A"
    ],
    "operatingDays": "DAILY"
  },
  {
    "number": "12604",
    "name": "Golconda SF Express",
    "trainType": "SUPERFAST",
    "sourceStationCode": "MAS",
    "destinationStationCode": "SC",
    "routeStationCodes": [
      "MAS",
      "SC"
    ],
    "departureTime": "22:30",
    "arrivalTime": "08:10",
    "arrivalDayOffset": 1,
    "durationMinutes": 580,
    "supportedClasses": [
      "3A",
      "2A",
      "1A"
    ],
    "operatingDays": "DAILY"
  },
  {
    "number": "12759",
    "name": "Hyderabad SF Express",
    "trainType": "SUPERFAST",
    "sourceStationCode": "MAS",
    "destinationStationCode": "SC",
    "routeStationCodes": [
      "MAS",
      "BZA",
      "SC"
    ],
    "departureTime": "20:00",
    "arrivalTime": "09:05",
    "arrivalDayOffset": 1,
    "durationMinutes": 785,
    "supportedClasses": [
      "SL",
      "3A"
    ],
    "operatingDays": "DAILY"
  },
  {
    "number": "17406",
    "name": "Rayalaseema Express",
    "trainType": "EXPRESS",
    "sourceStationCode": "MAS",
    "destinationStationCode": "SC",
    "routeStationCodes": [
      "MAS",
      "BZA",
      "SC"
    ],
    "departureTime": "17:45",
    "arrivalTime": "07:25",
    "arrivalDayOffset": 1,
    "durationMinutes": 820,
    "supportedClasses": [
      "SL",
      "3A"
    ],
    "operatingDays": "DAILY"
  },
  {
    "number": "17015",
    "name": "Circar Express",
    "trainType": "EXPRESS",
    "sourceStationCode": "MAS",
    "destinationStationCode": "SC",
    "routeStationCodes": [
      "MAS",
      "BZA",
      "SC"
    ],
    "departureTime": "16:30",
    "arrivalTime": "06:00",
    "arrivalDayOffset": 1,
    "durationMinutes": 810,
    "supportedClasses": [
      "SL",
      "3A"
    ],
    "operatingDays": "DAILY"
  },
  {
    "number": "12703",
    "name": "Chennai Hyderabad Express",
    "trainType": "EXPRESS",
    "sourceStationCode": "MAS",
    "destinationStationCode": "SC",
    "routeStationCodes": [
      "MAS",
      "BZA",
      "SC"
    ],
    "departureTime": "21:15",
    "arrivalTime": "10:00",
    "arrivalDayOffset": 1,
    "durationMinutes": 765,
    "supportedClasses": [
      "SL",
      "3A"
    ],
    "operatingDays": "DAILY"
  },
  {
    "number": "12841",
    "name": "Coastal SF Express",
    "trainType": "SUPERFAST",
    "sourceStationCode": "MAS",
    "destinationStationCode": "SC",
    "routeStationCodes": [
      "MAS",
      "VSKP",
      "SC"
    ],
    "departureTime": "06:00",
    "arrivalTime": "18:45",
    "arrivalDayOffset": 0,
    "durationMinutes": 765,
    "supportedClasses": [
      "SL",
      "3A"
    ],
    "operatingDays": "DAILY"
  },
  {
    "number": "12728",
    "name": "Godavari SF Express",
    "trainType": "SUPERFAST",
    "sourceStationCode": "MAS",
    "destinationStationCode": "SC",
    "routeStationCodes": [
      "MAS",
      "BZA",
      "SC"
    ],
    "departureTime": "19:30",
    "arrivalTime": "08:15",
    "arrivalDayOffset": 1,
    "durationMinutes": 765,
    "supportedClasses": [
      "3A",
      "2A"
    ],
    "operatingDays": "DAILY"
  },
  {
    "number": "12766",
    "name": "Nizam SF Express",
    "trainType": "SUPERFAST",
    "sourceStationCode": "MAS",
    "destinationStationCode": "SC",
    "routeStationCodes": [
      "MAS",
      "BZA",
      "SC"
    ],
    "departureTime": "20:15",
    "arrivalTime": "09:50",
    "arrivalDayOffset": 1,
    "durationMinutes": 815,
    "supportedClasses": [
      "SL",
      "3A"
    ],
    "operatingDays": "DAILY"
  },
  {
    "number": "17603",
    "name": "Kacheguda Express",
    "trainType": "EXPRESS",
    "sourceStationCode": "MAS",
    "destinationStationCode": "SC",
    "routeStationCodes": [
      "MAS",
      "BZA",
      "SC"
    ],
    "departureTime": "18:45",
    "arrivalTime": "07:30",
    "arrivalDayOffset": 1,
    "durationMinutes": 765,
    "supportedClasses": [
      "2A",
      "1A"
    ],
    "operatingDays": "DAILY"
  },
  {
    "number": "12864",
    "name": "Howrah SF Express",
    "trainType": "SUPERFAST",
    "sourceStationCode": "SBC",
    "destinationStationCode": "HWH",
    "routeStationCodes": [
      "SBC",
      "NGP",
      "HWH"
    ],
    "departureTime": "11:20",
    "arrivalTime": "17:50",
    "arrivalDayOffset": 1,
    "durationMinutes": 1830,
    "supportedClasses": [
      "SL",
      "3A",
      "2A"
    ],
    "operatingDays": "DAILY"
  },
  {
    "number": "12246",
    "name": "Duronto Express",
    "trainType": "SUPERFAST",
    "sourceStationCode": "SBC",
    "destinationStationCode": "HWH",
    "routeStationCodes": [
      "SBC",
      "HWH"
    ],
    "departureTime": "06:10",
    "arrivalTime": "11:20",
    "arrivalDayOffset": 1,
    "durationMinutes": 1750,
    "supportedClasses": [
      "3A",
      "2A"
    ],
    "operatingDays": "DAILY"
  },
  {
    "number": "18646",
    "name": "Howrah Passenger Express",
    "trainType": "EXPRESS",
    "sourceStationCode": "SBC",
    "destinationStationCode": "HWH",
    "routeStationCodes": [
      "SBC",
      "NGP",
      "HWH"
    ],
    "departureTime": "14:40",
    "arrivalTime": "23:10",
    "arrivalDayOffset": 1,
    "durationMinutes": 1950,
    "supportedClasses": [
      "SL",
      "3A"
    ],
    "operatingDays": "DAILY"
  },
  {
    "number": "20000",
    "name": "Kolkata Express",
    "trainType": "EXPRESS",
    "sourceStationCode": "MAS",
    "destinationStationCode": "HWH",
    "routeStationCodes": [
      "MAS",
      "HWH"
    ],
    "departureTime": "05:00",
    "arrivalTime": "09:00",
    "arrivalDayOffset": 0,
    "durationMinutes": 240,
    "supportedClasses": [
      "SL",
      "3A"
    ],
    "operatingDays": "DAILY"
  },
  {
    "number": "20001",
    "name": "Ahmedabad SF Express",
    "trainType": "SUPERFAST",
    "sourceStationCode": "SC",
    "destinationStationCode": "ADI",
    "routeStationCodes": [
      "SC",
      "ADI"
    ],
    "departureTime": "23:11",
    "arrivalTime": "04:04",
    "arrivalDayOffset": 1,
    "durationMinutes": 293,
    "supportedClasses": [
      "SL",
      "3A",
      "2A"
    ],
    "operatingDays": "DAILY"
  },
  {
    "number": "20002",
    "name": "Madurai Passenger",
    "trainType": "PASSENGER",
    "sourceStationCode": "HYB",
    "destinationStationCode": "MDU",
    "routeStationCodes": [
      "HYB",
      "MDU"
    ],
    "departureTime": "22:22",
    "arrivalTime": "04:08",
    "arrivalDayOffset": 1,
    "durationMinutes": 346,
    "supportedClasses": [
      "3A",
      "2A"
    ],
    "operatingDays": "DAILY"
  },
  {
    "number": "20003",
    "name": "Vijayawada Express",
    "trainType": "EXPRESS",
    "sourceStationCode": "SBC",
    "destinationStationCode": "BZA",
    "routeStationCodes": [
      "SBC",
      "BZA"
    ],
    "departureTime": "21:33",
    "arrivalTime": "04:12",
    "arrivalDayOffset": 1,
    "durationMinutes": 399,
    "supportedClasses": [
      "3A",
      "2A",
      "1A"
    ],
    "operatingDays": "DAILY"
  },
  {
    "number": "20004",
    "name": "Jaipur SF Express",
    "trainType": "SUPERFAST",
    "sourceStationCode": "CSMT",
    "destinationStationCode": "JP",
    "routeStationCodes": [
      "CSMT",
      "JP"
    ],
    "departureTime": "20:44",
    "arrivalTime": "04:16",
    "arrivalDayOffset": 1,
    "durationMinutes": 452,
    "supportedClasses": [
      "SL"
    ],
    "operatingDays": "DAILY"
  },
  {
    "number": "20005",
    "name": "Kochi Express",
    "trainType": "EXPRESS",
    "sourceStationCode": "BCT",
    "destinationStationCode": "ERS",
    "routeStationCodes": [
      "BCT",
      "ERS"
    ],
    "departureTime": "19:55",
    "arrivalTime": "04:20",
    "arrivalDayOffset": 1,
    "durationMinutes": 505,
    "supportedClasses": [
      "CC"
    ],
    "operatingDays": "DAILY"
  },
  {
    "number": "20006",
    "name": "Visakhapatnam SF Express",
    "trainType": "SUPERFAST",
    "sourceStationCode": "NDLS",
    "destinationStationCode": "VSKP",
    "routeStationCodes": [
      "NDLS",
      "VSKP"
    ],
    "departureTime": "18:06",
    "arrivalTime": "03:24",
    "arrivalDayOffset": 1,
    "durationMinutes": 558,
    "supportedClasses": [
      "SL",
      "3A",
      "2A",
      "1A"
    ],
    "operatingDays": "DAILY"
  },
  {
    "number": "20007",
    "name": "Bhopal Passenger",
    "trainType": "PASSENGER",
    "sourceStationCode": "HWH",
    "destinationStationCode": "BPL",
    "routeStationCodes": [
      "HWH",
      "BPL"
    ],
    "departureTime": "17:17",
    "arrivalTime": "03:28",
    "arrivalDayOffset": 1,
    "durationMinutes": 611,
    "supportedClasses": [
      "SL",
      "3A"
    ],
    "operatingDays": "DAILY"
  },
  {
    "number": "20008",
    "name": "Varanasi Express",
    "trainType": "EXPRESS",
    "sourceStationCode": "PUNE",
    "destinationStationCode": "BSB",
    "routeStationCodes": [
      "PUNE",
      "BSB"
    ],
    "departureTime": "16:28",
    "arrivalTime": "03:32",
    "arrivalDayOffset": 1,
    "durationMinutes": 664,
    "supportedClasses": [
      "SL",
      "3A",
      "2A"
    ],
    "operatingDays": "DAILY"
  },
  {
    "number": "20009",
    "name": "Bhubaneswar SF Express",
    "trainType": "SUPERFAST",
    "sourceStationCode": "ADI",
    "destinationStationCode": "BBS",
    "routeStationCodes": [
      "ADI",
      "BBS"
    ],
    "departureTime": "15:39",
    "arrivalTime": "03:36",
    "arrivalDayOffset": 1,
    "durationMinutes": 717,
    "supportedClasses": [
      "3A",
      "2A"
    ],
    "operatingDays": "DAILY"
  },
  {
    "number": "20010",
    "name": "Lucknow Express",
    "trainType": "EXPRESS",
    "sourceStationCode": "CBE",
    "destinationStationCode": "LKO",
    "routeStationCodes": [
      "CBE",
      "LKO"
    ],
    "departureTime": "14:50",
    "arrivalTime": "03:40",
    "arrivalDayOffset": 1,
    "durationMinutes": 770,
    "supportedClasses": [
      "3A",
      "2A",
      "1A"
    ],
    "operatingDays": "DAILY"
  },
  {
    "number": "20011",
    "name": "Patna SF Express",
    "trainType": "SUPERFAST",
    "sourceStationCode": "MDU",
    "destinationStationCode": "PNBE",
    "routeStationCodes": [
      "MDU",
      "PNBE"
    ],
    "departureTime": "13:01",
    "arrivalTime": "02:44",
    "arrivalDayOffset": 1,
    "durationMinutes": 823,
    "supportedClasses": [
      "SL"
    ],
    "operatingDays": "DAILY"
  },
  {
    "number": "20012",
    "name": "Mysuru Passenger",
    "trainType": "PASSENGER",
    "sourceStationCode": "ERS",
    "destinationStationCode": "MYS",
    "routeStationCodes": [
      "ERS",
      "MYS"
    ],
    "departureTime": "12:12",
    "arrivalTime": "02:48",
    "arrivalDayOffset": 1,
    "durationMinutes": 876,
    "supportedClasses": [
      "CC"
    ],
    "operatingDays": "DAILY"
  },
  {
    "number": "20013",
    "name": "Surat Express",
    "trainType": "EXPRESS",
    "sourceStationCode": "BZA",
    "destinationStationCode": "ST",
    "routeStationCodes": [
      "BZA",
      "ST"
    ],
    "departureTime": "11:23",
    "arrivalTime": "02:52",
    "arrivalDayOffset": 1,
    "durationMinutes": 929,
    "supportedClasses": [
      "SL",
      "3A",
      "2A",
      "1A"
    ],
    "operatingDays": "DAILY"
  },
  {
    "number": "20014",
    "name": "Guwahati SF Express",
    "trainType": "SUPERFAST",
    "sourceStationCode": "VSKP",
    "destinationStationCode": "GHY",
    "routeStationCodes": [
      "VSKP",
      "GHY"
    ],
    "departureTime": "10:34",
    "arrivalTime": "02:56",
    "arrivalDayOffset": 1,
    "durationMinutes": 982,
    "supportedClasses": [
      "SL",
      "3A"
    ],
    "operatingDays": "DAILY"
  },
  {
    "number": "20015",
    "name": "Nagpur Express",
    "trainType": "EXPRESS",
    "sourceStationCode": "JP",
    "destinationStationCode": "NGP",
    "routeStationCodes": [
      "JP",
      "NGP"
    ],
    "departureTime": "09:45",
    "arrivalTime": "03:00",
    "arrivalDayOffset": 1,
    "durationMinutes": 1035,
    "supportedClasses": [
      "SL",
      "3A",
      "2A"
    ],
    "operatingDays": "DAILY"
  },
  {
    "number": "20016",
    "name": "Indore SF Express",
    "trainType": "SUPERFAST",
    "sourceStationCode": "BPL",
    "destinationStationCode": "INDB",
    "routeStationCodes": [
      "BPL",
      "INDB"
    ],
    "departureTime": "08:56",
    "arrivalTime": "03:04",
    "arrivalDayOffset": 1,
    "durationMinutes": 1088,
    "supportedClasses": [
      "3A",
      "2A"
    ],
    "operatingDays": "DAILY"
  },
  {
    "number": "20017",
    "name": "Chandigarh Passenger",
    "trainType": "PASSENGER",
    "sourceStationCode": "LKO",
    "destinationStationCode": "CDG",
    "routeStationCodes": [
      "LKO",
      "CDG"
    ],
    "departureTime": "07:07",
    "arrivalTime": "11:08",
    "arrivalDayOffset": 0,
    "durationMinutes": 241,
    "supportedClasses": [
      "3A",
      "2A",
      "1A"
    ],
    "operatingDays": "DAILY"
  },
  {
    "number": "20018",
    "name": "Thiruvananthapuram Express",
    "trainType": "EXPRESS",
    "sourceStationCode": "BSB",
    "destinationStationCode": "TVC",
    "routeStationCodes": [
      "BSB",
      "TVC"
    ],
    "departureTime": "06:18",
    "arrivalTime": "11:12",
    "arrivalDayOffset": 0,
    "durationMinutes": 294,
    "supportedClasses": [
      "SL"
    ],
    "operatingDays": "DAILY"
  },
  {
    "number": "20019",
    "name": "Tiruchirapalli SF Express",
    "trainType": "SUPERFAST",
    "sourceStationCode": "PNBE",
    "destinationStationCode": "TPJ",
    "routeStationCodes": [
      "PNBE",
      "TPJ"
    ],
    "departureTime": "05:29",
    "arrivalTime": "11:16",
    "arrivalDayOffset": 0,
    "durationMinutes": 347,
    "supportedClasses": [
      "CC"
    ],
    "operatingDays": "DAILY"
  },
  {
    "number": "20020",
    "name": "Amritsar Express",
    "trainType": "EXPRESS",
    "sourceStationCode": "BBS",
    "destinationStationCode": "ASR",
    "routeStationCodes": [
      "BBS",
      "ASR"
    ],
    "departureTime": "23:40",
    "arrivalTime": "06:20",
    "arrivalDayOffset": 1,
    "durationMinutes": 400,
    "supportedClasses": [
      "SL",
      "3A",
      "2A",
      "1A"
    ],
    "operatingDays": "DAILY"
  },
  {
    "number": "20021",
    "name": "Salem SF Express",
    "trainType": "SUPERFAST",
    "sourceStationCode": "MYS",
    "destinationStationCode": "SA",
    "routeStationCodes": [
      "MYS",
      "SA"
    ],
    "departureTime": "22:51",
    "arrivalTime": "06:24",
    "arrivalDayOffset": 1,
    "durationMinutes": 453,
    "supportedClasses": [
      "SL",
      "3A"
    ],
    "operatingDays": "DAILY"
  },
  {
    "number": "20022",
    "name": "Warangal Passenger",
    "trainType": "PASSENGER",
    "sourceStationCode": "NGP",
    "destinationStationCode": "KZJ",
    "routeStationCodes": [
      "NGP",
      "KZJ"
    ],
    "departureTime": "21:02",
    "arrivalTime": "05:28",
    "arrivalDayOffset": 1,
    "durationMinutes": 506,
    "supportedClasses": [
      "SL",
      "3A",
      "2A"
    ],
    "operatingDays": "DAILY"
  },
  {
    "number": "20023",
    "name": "Jabalpur Express",
    "trainType": "EXPRESS",
    "sourceStationCode": "ST",
    "destinationStationCode": "JBP",
    "routeStationCodes": [
      "ST",
      "JBP"
    ],
    "departureTime": "20:13",
    "arrivalTime": "05:32",
    "arrivalDayOffset": 1,
    "durationMinutes": 559,
    "supportedClasses": [
      "3A",
      "2A"
    ],
    "operatingDays": "DAILY"
  },
  {
    "number": "20024",
    "name": "Ranchi SF Express",
    "trainType": "SUPERFAST",
    "sourceStationCode": "INDB",
    "destinationStationCode": "RNC",
    "routeStationCodes": [
      "INDB",
      "RNC"
    ],
    "departureTime": "19:24",
    "arrivalTime": "05:36",
    "arrivalDayOffset": 1,
    "durationMinutes": 612,
    "supportedClasses": [
      "3A",
      "2A",
      "1A"
    ],
    "operatingDays": "DAILY"
  },
  {
    "number": "20025",
    "name": "Nashik Express",
    "trainType": "EXPRESS",
    "sourceStationCode": "GHY",
    "destinationStationCode": "NK",
    "routeStationCodes": [
      "GHY",
      "NK"
    ],
    "departureTime": "18:35",
    "arrivalTime": "05:40",
    "arrivalDayOffset": 1,
    "durationMinutes": 665,
    "supportedClasses": [
      "SL"
    ],
    "operatingDays": "DAILY"
  },
  {
    "number": "20026",
    "name": "Raipur SF Express",
    "trainType": "SUPERFAST",
    "sourceStationCode": "CDG",
    "destinationStationCode": "R",
    "routeStationCodes": [
      "CDG",
      "R"
    ],
    "departureTime": "17:46",
    "arrivalTime": "05:44",
    "arrivalDayOffset": 1,
    "durationMinutes": 718,
    "supportedClasses": [
      "CC"
    ],
    "operatingDays": "DAILY"
  },
  {
    "number": "20027",
    "name": "Dehradun Passenger",
    "trainType": "PASSENGER",
    "sourceStationCode": "ASR",
    "destinationStationCode": "DDN",
    "routeStationCodes": [
      "ASR",
      "DDN"
    ],
    "departureTime": "16:57",
    "arrivalTime": "05:48",
    "arrivalDayOffset": 1,
    "durationMinutes": 771,
    "supportedClasses": [
      "SL",
      "3A",
      "2A",
      "1A"
    ],
    "operatingDays": "DAILY"
  },
  {
    "number": "20028",
    "name": "Kanpur Express",
    "trainType": "EXPRESS",
    "sourceStationCode": "TVC",
    "destinationStationCode": "CNB",
    "routeStationCodes": [
      "TVC",
      "CNB"
    ],
    "departureTime": "15:08",
    "arrivalTime": "04:52",
    "arrivalDayOffset": 1,
    "durationMinutes": 824,
    "supportedClasses": [
      "SL",
      "3A"
    ],
    "operatingDays": "DAILY"
  },
  {
    "number": "20029",
    "name": "Gwalior SF Express",
    "trainType": "SUPERFAST",
    "sourceStationCode": "SA",
    "destinationStationCode": "GWL",
    "routeStationCodes": [
      "SA",
      "GWL"
    ],
    "departureTime": "14:19",
    "arrivalTime": "04:56",
    "arrivalDayOffset": 1,
    "durationMinutes": 877,
    "supportedClasses": [
      "SL",
      "3A",
      "2A"
    ],
    "operatingDays": "DAILY"
  },
  {
    "number": "20030",
    "name": "Agra Express",
    "trainType": "EXPRESS",
    "sourceStationCode": "TPJ",
    "destinationStationCode": "AGC",
    "routeStationCodes": [
      "TPJ",
      "AGC"
    ],
    "departureTime": "13:30",
    "arrivalTime": "05:00",
    "arrivalDayOffset": 1,
    "durationMinutes": 930,
    "supportedClasses": [
      "3A",
      "2A"
    ],
    "operatingDays": "DAILY"
  },
  {
    "number": "20031",
    "name": "Prayagraj SF Express",
    "trainType": "SUPERFAST",
    "sourceStationCode": "KZJ",
    "destinationStationCode": "PRYJ",
    "routeStationCodes": [
      "KZJ",
      "PRYJ"
    ],
    "departureTime": "12:41",
    "arrivalTime": "05:04",
    "arrivalDayOffset": 1,
    "durationMinutes": 983,
    "supportedClasses": [
      "3A",
      "2A",
      "1A"
    ],
    "operatingDays": "DAILY"
  },
  {
    "number": "20032",
    "name": "Jodhpur Passenger",
    "trainType": "PASSENGER",
    "sourceStationCode": "NK",
    "destinationStationCode": "JU",
    "routeStationCodes": [
      "NK",
      "JU"
    ],
    "departureTime": "11:52",
    "arrivalTime": "05:08",
    "arrivalDayOffset": 1,
    "durationMinutes": 1036,
    "supportedClasses": [
      "SL"
    ],
    "operatingDays": "DAILY"
  },
  {
    "number": "20033",
    "name": "Rajkot Express",
    "trainType": "EXPRESS",
    "sourceStationCode": "JBP",
    "destinationStationCode": "RJT",
    "routeStationCodes": [
      "JBP",
      "RJT"
    ],
    "departureTime": "10:03",
    "arrivalTime": "04:12",
    "arrivalDayOffset": 1,
    "durationMinutes": 1089,
    "supportedClasses": [
      "CC"
    ],
    "operatingDays": "DAILY"
  },
  {
    "number": "20034",
    "name": "Nellore SF Express",
    "trainType": "SUPERFAST",
    "sourceStationCode": "R",
    "destinationStationCode": "NLR",
    "routeStationCodes": [
      "R",
      "NLR"
    ],
    "departureTime": "09:14",
    "arrivalTime": "13:16",
    "arrivalDayOffset": 0,
    "durationMinutes": 242,
    "supportedClasses": [
      "SL",
      "3A",
      "2A",
      "1A"
    ],
    "operatingDays": "DAILY"
  },
  {
    "number": "20035",
    "name": "Udaipur Express",
    "trainType": "EXPRESS",
    "sourceStationCode": "RNC",
    "destinationStationCode": "UDZ",
    "routeStationCodes": [
      "RNC",
      "UDZ"
    ],
    "departureTime": "08:25",
    "arrivalTime": "13:20",
    "arrivalDayOffset": 0,
    "durationMinutes": 295,
    "supportedClasses": [
      "SL",
      "3A"
    ],
    "operatingDays": "DAILY"
  },
  {
    "number": "20036",
    "name": "Vadodara SF Express",
    "trainType": "SUPERFAST",
    "sourceStationCode": "DDN",
    "destinationStationCode": "BRC",
    "routeStationCodes": [
      "DDN",
      "BRC"
    ],
    "departureTime": "07:36",
    "arrivalTime": "13:24",
    "arrivalDayOffset": 0,
    "durationMinutes": 348,
    "supportedClasses": [
      "SL",
      "3A",
      "2A"
    ],
    "operatingDays": "DAILY"
  },
  {
    "number": "20037",
    "name": "Rajahmundry Passenger",
    "trainType": "PASSENGER",
    "sourceStationCode": "AGC",
    "destinationStationCode": "RJY",
    "routeStationCodes": [
      "AGC",
      "RJY"
    ],
    "departureTime": "06:47",
    "arrivalTime": "13:28",
    "arrivalDayOffset": 0,
    "durationMinutes": 401,
    "supportedClasses": [
      "3A",
      "2A"
    ],
    "operatingDays": "DAILY"
  },
  {
    "number": "20038",
    "name": "Hubballi Express",
    "trainType": "EXPRESS",
    "sourceStationCode": "CNB",
    "destinationStationCode": "UBL",
    "routeStationCodes": [
      "CNB",
      "UBL"
    ],
    "departureTime": "05:58",
    "arrivalTime": "13:32",
    "arrivalDayOffset": 0,
    "durationMinutes": 454,
    "supportedClasses": [
      "3A",
      "2A",
      "1A"
    ],
    "operatingDays": "DAILY"
  },
  {
    "number": "20039",
    "name": "Guntur SF Express",
    "trainType": "SUPERFAST",
    "sourceStationCode": "PRYJ",
    "destinationStationCode": "GNT",
    "routeStationCodes": [
      "PRYJ",
      "GNT"
    ],
    "departureTime": "23:09",
    "arrivalTime": "07:36",
    "arrivalDayOffset": 1,
    "durationMinutes": 507,
    "supportedClasses": [
      "SL"
    ],
    "operatingDays": "DAILY"
  },
  {
    "number": "20040",
    "name": "Tirupati Express",
    "trainType": "EXPRESS",
    "sourceStationCode": "GWL",
    "destinationStationCode": "TPTY",
    "routeStationCodes": [
      "GWL",
      "TPTY"
    ],
    "departureTime": "22:20",
    "arrivalTime": "07:40",
    "arrivalDayOffset": 1,
    "durationMinutes": 560,
    "supportedClasses": [
      "CC"
    ],
    "operatingDays": "DAILY"
  },
  {
    "number": "20041",
    "name": "Mangaluru SF Express",
    "trainType": "SUPERFAST",
    "sourceStationCode": "JU",
    "destinationStationCode": "MAQ",
    "routeStationCodes": [
      "JU",
      "MAQ"
    ],
    "departureTime": "21:31",
    "arrivalTime": "07:44",
    "arrivalDayOffset": 1,
    "durationMinutes": 613,
    "supportedClasses": [
      "SL",
      "3A",
      "2A",
      "1A"
    ],
    "operatingDays": "DAILY"
  },
  {
    "number": "20042",
    "name": "Chennai Passenger",
    "trainType": "PASSENGER",
    "sourceStationCode": "UDZ",
    "destinationStationCode": "MAS",
    "routeStationCodes": [
      "UDZ",
      "MAS"
    ],
    "departureTime": "20:42",
    "arrivalTime": "07:48",
    "arrivalDayOffset": 1,
    "durationMinutes": 666,
    "supportedClasses": [
      "SL",
      "3A"
    ],
    "operatingDays": "DAILY"
  },
  {
    "number": "20043",
    "name": "Hyderabad Express",
    "trainType": "EXPRESS",
    "sourceStationCode": "RJT",
    "destinationStationCode": "HYB",
    "routeStationCodes": [
      "RJT",
      "HYB"
    ],
    "departureTime": "19:53",
    "arrivalTime": "07:52",
    "arrivalDayOffset": 1,
    "durationMinutes": 719,
    "supportedClasses": [
      "SL",
      "3A",
      "2A"
    ],
    "operatingDays": "DAILY"
  },
  {
    "number": "20044",
    "name": "Mumbai SF Express",
    "trainType": "SUPERFAST",
    "sourceStationCode": "BRC",
    "destinationStationCode": "CSMT",
    "routeStationCodes": [
      "BRC",
      "CSMT"
    ],
    "departureTime": "18:04",
    "arrivalTime": "06:56",
    "arrivalDayOffset": 1,
    "durationMinutes": 772,
    "supportedClasses": [
      "3A",
      "2A"
    ],
    "operatingDays": "DAILY"
  },
  {
    "number": "20045",
    "name": "Hyderabad Express",
    "trainType": "EXPRESS",
    "sourceStationCode": "NLR",
    "destinationStationCode": "SC",
    "routeStationCodes": [
      "NLR",
      "SC"
    ],
    "departureTime": "17:15",
    "arrivalTime": "07:00",
    "arrivalDayOffset": 1,
    "durationMinutes": 825,
    "supportedClasses": [
      "3A",
      "2A",
      "1A"
    ],
    "operatingDays": "DAILY"
  },
  {
    "number": "20046",
    "name": "Bengaluru SF Express",
    "trainType": "SUPERFAST",
    "sourceStationCode": "RJY",
    "destinationStationCode": "SBC",
    "routeStationCodes": [
      "RJY",
      "SBC"
    ],
    "departureTime": "16:26",
    "arrivalTime": "07:04",
    "arrivalDayOffset": 1,
    "durationMinutes": 878,
    "supportedClasses": [
      "SL"
    ],
    "operatingDays": "DAILY"
  },
  {
    "number": "20047",
    "name": "Mumbai Passenger",
    "trainType": "PASSENGER",
    "sourceStationCode": "TPTY",
    "destinationStationCode": "BCT",
    "routeStationCodes": [
      "TPTY",
      "BCT"
    ],
    "departureTime": "15:37",
    "arrivalTime": "07:08",
    "arrivalDayOffset": 1,
    "durationMinutes": 931,
    "supportedClasses": [
      "CC"
    ],
    "operatingDays": "DAILY"
  },
  {
    "number": "20048",
    "name": "Kolkata Express",
    "trainType": "EXPRESS",
    "sourceStationCode": "UBL",
    "destinationStationCode": "HWH",
    "routeStationCodes": [
      "UBL",
      "HWH"
    ],
    "departureTime": "14:48",
    "arrivalTime": "07:12",
    "arrivalDayOffset": 1,
    "durationMinutes": 984,
    "supportedClasses": [
      "SL",
      "3A",
      "2A",
      "1A"
    ],
    "operatingDays": "DAILY"
  },
  {
    "number": "20049",
    "name": "Ahmedabad SF Express",
    "trainType": "SUPERFAST",
    "sourceStationCode": "MAQ",
    "destinationStationCode": "ADI",
    "routeStationCodes": [
      "MAQ",
      "ADI"
    ],
    "departureTime": "13:59",
    "arrivalTime": "07:16",
    "arrivalDayOffset": 1,
    "durationMinutes": 1037,
    "supportedClasses": [
      "SL",
      "3A"
    ],
    "operatingDays": "DAILY"
  },
  {
    "number": "20050",
    "name": "Delhi Express",
    "trainType": "EXPRESS",
    "sourceStationCode": "GNT",
    "destinationStationCode": "NDLS",
    "routeStationCodes": [
      "GNT",
      "NDLS"
    ],
    "departureTime": "12:10",
    "arrivalTime": "06:20",
    "arrivalDayOffset": 1,
    "durationMinutes": 1090,
    "supportedClasses": [
      "SL",
      "3A",
      "2A"
    ],
    "operatingDays": "DAILY"
  },
  {
    "number": "20051",
    "name": "Pune SF Express",
    "trainType": "SUPERFAST",
    "sourceStationCode": "MAS",
    "destinationStationCode": "PUNE",
    "routeStationCodes": [
      "MAS",
      "PUNE"
    ],
    "departureTime": "11:21",
    "arrivalTime": "15:24",
    "arrivalDayOffset": 0,
    "durationMinutes": 243,
    "supportedClasses": [
      "3A",
      "2A"
    ],
    "operatingDays": "DAILY"
  },
  {
    "number": "20052",
    "name": "Coimbatore Passenger",
    "trainType": "PASSENGER",
    "sourceStationCode": "SC",
    "destinationStationCode": "CBE",
    "routeStationCodes": [
      "SC",
      "CBE"
    ],
    "departureTime": "10:32",
    "arrivalTime": "15:28",
    "arrivalDayOffset": 0,
    "durationMinutes": 296,
    "supportedClasses": [
      "3A",
      "2A",
      "1A"
    ],
    "operatingDays": "DAILY"
  },
  {
    "number": "20053",
    "name": "Kochi Express",
    "trainType": "EXPRESS",
    "sourceStationCode": "HYB",
    "destinationStationCode": "ERS",
    "routeStationCodes": [
      "HYB",
      "ERS"
    ],
    "departureTime": "09:43",
    "arrivalTime": "15:32",
    "arrivalDayOffset": 0,
    "durationMinutes": 349,
    "supportedClasses": [
      "SL"
    ],
    "operatingDays": "DAILY"
  },
  {
    "number": "20054",
    "name": "Visakhapatnam SF Express",
    "trainType": "SUPERFAST",
    "sourceStationCode": "SBC",
    "destinationStationCode": "VSKP",
    "routeStationCodes": [
      "SBC",
      "VSKP"
    ],
    "departureTime": "08:54",
    "arrivalTime": "15:36",
    "arrivalDayOffset": 0,
    "durationMinutes": 402,
    "supportedClasses": [
      "CC"
    ],
    "operatingDays": "DAILY"
  }
];
