/**
 * AUTO-GENERATED by scripts/generateMockData.ts — do not hand-edit.
 * Regenerate with: npm run generate:data
 *
 * Conforms to the data contract in spec/04-data-spec.md.
 */

import type { User } from '../types/domain';

export const users: User[] = [
  {
    "id": "user_1",
    "displayName": "Aravind",
    "preferences": {
      "preferredClass": "3A",
      "berthPreference": "LOWER",
      "travelPriority": "CONFIRMATION"
    },
    "savedPassengerIds": [
      "passenger_1",
      "passenger_2"
    ]
  },
  {
    "id": "user_2",
    "displayName": "Suresh",
    "preferences": {
      "preferredClass": "SL",
      "berthPreference": "NO_PREFERENCE",
      "travelPriority": "PRICE"
    },
    "savedPassengerIds": [
      "passenger_3",
      "passenger_4"
    ]
  },
  {
    "id": "user_3",
    "displayName": "Karthik",
    "preferences": {
      "preferredClass": "2A",
      "berthPreference": "SIDE_LOWER",
      "travelPriority": "SPEED"
    },
    "savedPassengerIds": [
      "passenger_5"
    ]
  }
];
